// TypesFromSerializers CacheKey 1a8580098d94440c8979b48cf158e909
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from '../Categories/Options'
import type Contact from '../Contact'

declare global {
  namespace Schema {
    interface EmailsEdit {
      id: number
      category: CategoriesOptions
      category_id?: number
      contact: Contact
      contact_id: number
      email: string
      notes?: string
    }
  }
}
