// TypesFromSerializers CacheKey 235b1a5203b89c3e42fa1e43200db27a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from '../Categories/Options'

declare global {
  namespace Schema {
    interface EmailsFormData {
      id?: number
      category: CategoriesOptions
      category_id?: number
      contact_id: number
      email: string
      notes?: string
    }
  }
}
