// TypesFromSerializers CacheKey 0dda981afc3cb581b10dc7d653366833
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface EmailsFormData {
			id?: number
			category_id?: number
			contact_id: number
			email?: string
		}

	}
}
