// TypesFromSerializers CacheKey 9275706d447eb58ce08037bb2e925ed1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CompaniesBasic {
      id: number
      created_at: string | Date
      default_currency: string
      name: string
      settings: Record<string, string>
      slug: string
      updated_at: string | Date
    }
  }
}
