// TypesFromSerializers CacheKey aef19d4351478662b2a360b4c0e3dead
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CompaniesCounts {
      id?: number
      slug?: string
      counts: {
    locations: number
    items: number
    accessories: number
    consumables: number
    components: number
    departments: number
    licenses: number
    contracts: number
    people: number
    vendors: number
    manufacturers: number
  }
      default_currency: string
      name: string
      settings: Record<string, string>
    }
  }
}
