// TypesFromSerializers CacheKey 9807df0236dc118c7b2afc42a23e16c8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface CompaniesDashboard {
			id?: number
			counts: {
    locations: number
    items: number
    accessories: number
    consumables: number
    components: number
    departments: number
    licenses: number
    contracts: number
    people: number
    vendors: number
    manufacturers: number
  }
		}

	}
}
