// TypesFromSerializers CacheKey d78b14cf097fda39d5d4396c5c281801
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ContactsFormData from '../Contacts/FormData'

declare global {
  namespace Schema {
    interface CompaniesEdit {
      id: number
      contact: ContactsFormData
      default_currency: string
      name: string
      settings: Record<string, string>
      slug: string
    }
  }
}
