// TypesFromSerializers CacheKey b44a53f2ae44b5c51edeb70071ed2bab
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Contact } from '../Contact'

declare global {
  namespace Schema {
    interface CompaniesEdit {
      id: number
      contact: Contact
      default_currency: string
      name: string
      settings: Record<string, string>
      slug: string
    }
  }
}
