// TypesFromSerializers CacheKey 7eb5ac48cf2e1b2d5cd6caacdde5790d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Contact } from '../Contact'

declare export global {
	declare namespace Schema {
		export interface CompaniesEdit {
			id?: number
			contact: Contact
			name: string
			settings: unknown
			slug: string
		}

	}
}
