// TypesFromSerializers CacheKey 93cc580d1cd6a0e828fcb30bd8897d7a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ContactsFormData from '../Contacts/FormData'

declare global {
  namespace Schema {
    interface CompaniesFormData {
      id?: number
      slug?: string
      contact: ContactsFormData
      default_currency: string
      name: string
      settings: Record<string, string>
    }
  }
}
