// TypesFromSerializers CacheKey 76f9638bb1dac217016ed9c1fa06fcaf
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ContactsFormData from '../Contacts/FormData'

declare global {
  namespace Schema {
    interface CompaniesFormData {
      id?: number
      slug?: string
      contact: ContactsFormData
      default_currency: string
      name: string
      settings: Record<string, string>
    }
  }
}
