// TypesFromSerializers CacheKey bd22e255ea0bef7846760fcda6cc152c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { ContactsFormData } from '../Contacts/FormData'

declare global {
  namespace Schema {
    interface CompaniesFormData {
      id?: number
      contact: ContactsFormData
      name: string
    }
  }
}
