// TypesFromSerializers CacheKey 4932bd48860539fb42e90ce71e05ca51
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CompaniesIndex {
      id?: number
      counts: {
    locations: number
    items: number
    accessories: number
    consumables: number
    components: number
    departments: number
    licenses: number
    contracts: number
    people: number
    vendors: number
    manufacturers: number
  }
      created_at: string | Date
      name: string
      settings: Record<string, string>
      slug: string
      updated_at: string | Date
    }
  }
}
