// TypesFromSerializers CacheKey ec27a3cbfc5a4555267a00a28155f215
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface CompaniesIndex {
  id?: number
  counts: unknown
  createdAt: string | Date
  name: string
  settings: unknown
  slug: string
  updatedAt: string | Date
}

