// TypesFromSerializers CacheKey 0fb7025bc57ee2809679dbb8a6e49590
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface CompaniesNew {
  id?: number
  name: string
}

