// TypesFromSerializers CacheKey aa454ac6b9239aeb6f487c59dc829224
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CompaniesOptions {
      id: number
      name: string
      slug: string
    }
  }
}
