// TypesFromSerializers CacheKey b283b2a73d9947c6c0e1f4312e45df21
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CompaniesOptions {
      id: number
      name: string
      slug: string
    }
  }
}
