// TypesFromSerializers CacheKey 5d7a24b30c9f6d33cfc9f444e56ea969
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Contact from '../Contact'

declare global {
  namespace Schema {
    interface CompaniesShow {
      id: number
      contact: Contact
      counts: {
    locations: number
    items: number
    accessories: number
    consumables: number
    components: number
    departments: number
    licenses: number
    contracts: number
    people: number
    vendors: number
    manufacturers: number
  }
      created_at: string | Date
      default_currency: string
      name: string
      settings: Record<string, string>
      slug: string
      updated_at: string | Date
    }
  }
}
