// TypesFromSerializers CacheKey d1ef87c6d3ecbe3e481d44eefd8882cf
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Contact } from '../Contact'

declare export global {
	declare namespace Schema {
		export interface CompaniesShow {
			id?: number
			contact: Contact
			counts: unknown
			created_at: string | Date
			name: string
			settings: unknown
			slug: string
			updated_at: string | Date
		}

	}
}
