// TypesFromSerializers CacheKey 73d74a0bf704546c35df4a8aa79326ff
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type TicketStatus from '../TicketStatus'

declare global {
  namespace Schema {
    interface TicketsBasic {
      id: number
      asset_id?: number
      created_at: string | Date
      created_by_id?: number
      description?: string
      number: number
      primary_contact_id?: number
      priority: "urgent" | "high" | "standard" | "low"
      status: TicketStatus
      status_id?: number
      subject: string
      updated_at: string | Date
    }
  }
}
