// TypesFromSerializers CacheKey bde965814299d7bda53098c1d120a902
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type AssetsOptions from '../Assets/Options'
import type Person from '../Person'
import type TicketAssignmentsFormData from '../TicketAssignments/FormData'
import type TicketStatusesFormData from '../TicketStatuses/FormData'

declare global {
  namespace Schema {
    interface TicketsEdit {
      id: number
      asset?: AssetsOptions
      asset_id?: number
      assignees?: Person[]
      assignments?: TicketAssignmentsFormData[]
      created_by_id?: number
      description?: string
      number: number
      primary_contact_id?: number
      priority: "urgent" | "high" | "standard" | "low"
      status?: TicketStatusesFormData
      status_id?: number
      subject: string
    }
  }
}
