// TypesFromSerializers CacheKey 95fee3a527c6adfe7c07d85d6a446409
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { TicketAssignmentsEdit } from '../TicketAssignments/Edit'

declare global {
	 declare namespace Schema {
		export interface TicketsEdit {
			id?: number
			assetId?: number
			assignments: TicketAssignmentsEdit[]
			description?: string
			primaryContactId?: number
			subject: string
		}

	}
}
