// TypesFromSerializers CacheKey e4e5670b6951a8a809c1f5216894f6f4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'
import type TicketAssignmentsEdit from '../TicketAssignments/Edit'
import type TicketStatusesFormData from '../TicketStatuses/FormData'

declare global {
  namespace Schema {
    interface TicketsEdit {
      id: number
      asset_id?: number
      assignees: Person[]
      assignments: TicketAssignmentsEdit[]
      description?: string
      number: number
      primary_contact_id?: number
      status: TicketStatusesFormData
      subject: string
    }
  }
}
