// TypesFromSerializers CacheKey 5c7deb732b68b35de32a1c453cf669af
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type TicketAssignment from '../TicketAssignment'

export default interface TicketsEdit {
  id?: number
  assetId?: number
  assignments: TicketAssignment[]
  description?: string
  primaryContactId?: number
  subject: string
}

