// TypesFromSerializers CacheKey d1dc510b9e906d83632f3377b9db6845
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Person } from '../Person'
import type { TicketAssignmentsFormData } from '../TicketAssignments/FormData'
import type { TicketStatusesFormData } from '../TicketStatuses/FormData'

declare global {
  namespace Schema {
    interface TicketsFormData {
      id?: number
      asset_id?: number
      assignees: Person[]
      assignments: TicketAssignmentsFormData[]
      description?: string
      number: number
      primary_contact_id?: number
      status: TicketStatusesFormData
      subject: string
    }
  }
}
