// TypesFromSerializers CacheKey 864f03865cc2795503a4adfabd58fab3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Asset from '../Asset'
import type Person from '../Person'
import type TicketMessage from '../TicketMessage'
import type TicketStatus from '../TicketStatus'

export default interface TicketsIndex {
  id?: number
  asset: Asset
  assetId?: number
  assignees: Person[]
  createdAt: string | Date
  createdBy: Person
  description?: string
  messages: TicketMessage[]
  primaryContact: Person
  primaryContactId?: number
  status: TicketStatus
  subject: string
  updatedAt: string | Date
}

