// TypesFromSerializers CacheKey c3dc714413730c681f57338496f856c8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Asset from '../Asset'
import type Person from '../Person'
import type TicketMessage from '../TicketMessage'
import type TicketStatus from '../TicketStatus'

declare global {
  namespace Schema {
    interface TicketsIndex {
      id: number
      asset: Asset
      asset_id?: number
      assignees: Person[]
      created_at: string | Date
      created_by: Person
      created_by_id?: number
      description?: string
      messages: TicketMessage[]
      number: number
      primary_contact: Person
      primary_contact_id?: number
      priority?: number
      status: TicketStatus
      status_id?: number
      subject: string
      updated_at: string | Date
    }
  }
}
