// TypesFromSerializers CacheKey 0ef7b7991f30f7df0046b2c952434666
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type TicketAssignment from '../TicketAssignment'
import type TicketStatus from '../TicketStatus'

export default interface TicketsNew {
  id?: number
  assetId?: number
  assignments: TicketAssignment[]
  description?: string
  primaryContactId?: number
  status: TicketStatus
  subject: string
}

