// TypesFromSerializers CacheKey 508aec7b573d1a94cf53394d12b2a766
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface TicketsOptions {
      id: number
      subject: string
    }
  }
}
