// TypesFromSerializers CacheKey a438564e5058d00a1299ce1513202c3f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface TicketsOptions {
      id: number
      subject: string
    }
  }
}
