// TypesFromSerializers CacheKey ad2f427a6157bea5b0b65ef93cd8f459
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type AssetsBasic from '../Assets/Basic'
import type Person from '../Person'
import type TicketMessage from '../TicketMessage'
import type TicketStatus from '../TicketStatus'

declare global {
  namespace Schema {
    interface TicketsShow {
      id: number
      asset: AssetsBasic
      asset_id?: number
      assignees: Person[]
      created_at: string | Date
      created_by: Person
      created_by_id?: number
      description?: string
      messages: TicketMessage[]
      number: number
      primary_contact: Person
      primary_contact_id?: number
      priority: "urgent" | "high" | "standard" | "low"
      status: TicketStatus
      status_id?: number
      subject: string
      updated_at: string | Date
    }
  }
}
