// TypesFromSerializers CacheKey ddb0e3aec84b648dbbc1f309c99e468d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PeopleBasic from '../People/Basic'

declare global {
  namespace Schema {
    interface TicketsSpotlight {
      id: string
      asset_id?: number
      created_by_id?: number
      description?: string
      number: number
      primary_contact: PeopleBasic
      primary_contact_id?: number
      priority: "urgent" | "high" | "standard" | "low"
      status_id?: number
      subject: string
    }
  }
}
