// TypesFromSerializers CacheKey bf3d1a6c1918d0d953f3b6a8ade5b4c5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'
import type Ticket from '../Ticket'

declare global {
  namespace Schema {
    interface TicketAssignmentsEdit {
      id?: number
      person?: Person
      person_id: number
      ticket?: Ticket
      ticket_id: number
    }
  }
}
