// TypesFromSerializers CacheKey 56f39e2bb2ba19b747e125e2829983c0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface TicketAssignmentsEdit {
  id?: number
  personId: number
  ticketId: number
}

