// TypesFromSerializers CacheKey 194b9c3aa169c03d2f59c97b3f577c41
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface TicketAssignmentsFormData {
			id?: number
			person_id: number
			ticket_id: number
		}

	}
}
