// TypesFromSerializers CacheKey 65f690d17952f652c9b4686ca4fefcee
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'
import type Ticket from '../Ticket'

declare global {
  namespace Schema {
    interface TicketAssignmentsFormData {
      id?: number
      person?: Person
      person_id: number
      ticket?: Ticket
      ticket_id: number
    }
  }
}
