// TypesFromSerializers CacheKey 802c41c6e2c30ffd272f9f7fa30a932d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Person } from '../Person'
import type { Ticket } from '../Ticket'

declare global {
	 declare namespace Schema {
		export interface TicketAssignmentsIndex {
			id?: number
			createdAt: string | Date
			person: Person
			personId: number
			ticket: Ticket
			ticketId: number
			updatedAt: string | Date
		}

	}
}
