// TypesFromSerializers CacheKey 220a3fd970b0d58771c9e87f1be95ab5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface TicketAssignmentsNew {
  id?: number
  personId: number
  ticketId: number
}

