// TypesFromSerializers CacheKey 090cf8bde2024b13579a1336f99b6279
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'
import type Ticket from '../Ticket'

declare global {
  namespace Schema {
    interface TicketAssignmentsShow {
      id: unknown
      created_at: unknown
      person: Person
      ticket: Ticket
      updated_at: unknown
    }
  }
}
