// TypesFromSerializers CacheKey 45df012f2f6a8517fad6ae51de1d0b9c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from '../Categories/Options'

declare global {
  namespace Schema {
    interface DocumentationsEdit {
      id: number
      body?: string
      category: CategoriesOptions
      category_id: number
      created_by_id?: number
      documentable_id: number
      documentable_name: string
      documentable_type: string
      slug: string
      title: string
    }
  }
}
