// TypesFromSerializers CacheKey bd88ab4883a42d68fa5c2ce47d19c1e0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'

declare global {
  namespace Schema {
    interface DocumentationsEdit {
      id: number
      body?: string
      created_by: Person
      documentable_id: number
      documentable_type: string
      slug: string
      title?: string
    }
  }
}
