// TypesFromSerializers CacheKey 72340b992d0b6891906803bf143fe3fe
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from '../Categories/Options'

declare global {
  namespace Schema {
    interface DocumentationsEdit {
      id: number
      body?: string
      category: CategoriesOptions
      category_id: number
      created_by_id?: number
      documentable_id: number
      documentable_name: string
      documentable_type: string
      slug: string
      title: string
    }
  }
}
