// TypesFromSerializers CacheKey 1283c9ab8c9a70026cbe770a487cccd4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from '../Categories/Options'
import type Person from '../Person'

declare global {
  namespace Schema {
    interface DocumentationsIndex {
      id: number
      body?: string
      category: CategoriesOptions
      category_id: number
      created_at: string | Date
      created_by: Person
      created_by_id?: number
      documentable_id: number
      documentable_name: string
      documentable_type: string
      route: string
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
