// TypesFromSerializers CacheKey b33c2de97e2f37a28a29a27ba2bc1d5e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from '../Categories/Options'
import type PeopleBasic from '../People/Basic'

declare global {
  namespace Schema {
    interface DocumentationsShow {
      id: number
      body?: string
      category: CategoriesOptions
      category_id: number
      created_at: string | Date
      created_by: PeopleBasic
      created_by_id?: number
      documentable_id: number
      documentable_name: string
      documentable_route: string
      documentable_type: string
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
