// TypesFromSerializers CacheKey c6d65e7338932f7ad7ebf9585b35ddb9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Person } from '../Person'

declare global {
  namespace Schema {
    interface DocumentationsShow {
      id: number
      body?: string
      created_at: string | Date
      created_by: Person
      slug?: string
      title?: string
      updated_at: string | Date
    }
  }
}
