// TypesFromSerializers CacheKey 4f7b988827f59095a7ffb621b2105ed1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ManufacturersBasic {
      id: number
      created_at: string | Date
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
