// TypesFromSerializers CacheKey 9f3e5fe9d092516313f6521bd8285e80
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ManufacturersCounts {
      id?: number
      slug?: string
      counts: {
    models: number
    items: number
    accessories: number
    consumables: number
    components: number
  }
      name: string
    }
  }
}
