// TypesFromSerializers CacheKey e3aa59ebb53148966d62c9e2c807fd24
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface ManufacturersEdit {
			id: number
			name?: string
			slug: string
		}

	}
}
