// TypesFromSerializers CacheKey fc120ef8ef3ec2e10eba5ca4f5bceb65
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface ManufacturersEdit {
			id: number
			slug?: string
			name?: string
		}

	}
}
