// TypesFromSerializers CacheKey 8e64e4441bed81c84f64df0769a75183
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ManufacturersEdit {
      id: number
      name: string
      slug: string
    }
  }
}
