// TypesFromSerializers CacheKey b97e819d66438bcdbb1ad6097e366191
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ManufacturersFormData {
      id?: number
      slug?: string
      name?: string
    }
  }
}
