// TypesFromSerializers CacheKey ada0c3cb1e4bd0f8f1f3f9af1c9fb9c3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface ManufacturersIndex {
			id: number
			counts: {
    models: number
    items: number
    accessories: number
    consumables: number
    components: number
  }
			created_at: string | Date
			name?: string
			slug: string
			updated_at: string | Date
		}

	}
}
