// TypesFromSerializers CacheKey aab6177d59b5dba2a2d337b3813f26e6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ManufacturersIndex {
  id: number
  slug?: string
  counts: unknown
  createdAt: string | Date
  name?: string
  updatedAt: string | Date
}

