// TypesFromSerializers CacheKey 2d87d10e88db492de1c2bfab7da40e15
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ManufacturersIndex {
      id: number
      counts: {
    models: number
    items: number
    accessories: number
    consumables: number
    components: number
  }
      created_at: string | Date
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
