// TypesFromSerializers CacheKey 91d1c2fa254d4c9751634941c4e3be8d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ManufacturersOptions {
      id: number
      name: string
      slug: string
    }
  }
}
