// TypesFromSerializers CacheKey dc414ed2c6eab649ecdf400b305a8031
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface ManufacturersOptions {
			id: number
			name?: string
		}

	}
}
