// TypesFromSerializers CacheKey 60529c8eb02af5603f7c3ca576fa31c2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Contact } from '../Contact'

declare export global {
	declare namespace Schema {
		export interface ManufacturersShow {
			id: number
			slug?: string
			accessories_count: unknown
			components_count: unknown
			consumables_count: unknown
			contact: Contact
			created_at: string | Date
			items_count: unknown
			name?: string
			updated_at: string | Date
		}

	}
}
