// TypesFromSerializers CacheKey eedb3aec23d5e60148df445544178596
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface AssignableConsume {
      id: number
      name: string
      qty_available: number
    }
  }
}
