// TypesFromSerializers CacheKey 412b6ba547609b00afd08f35b22d6863
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface AssignableConsume {
			id?: unknown
			qty_available: number
		}

	}
}
