// TypesFromSerializers CacheKey 05c782ba5465cbf8b29395cd4e1f09a4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface AssignableConsume {
      id: number
      name: string
      qty_available: number
    }
  }
}
