// TypesFromSerializers CacheKey 91ecc95b75d8d7fb9eb6991e1e1011a1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface AssignableQuantity {
      id: number
      name: string
      qty_available: number
    }
  }
}
