// TypesFromSerializers CacheKey 2720f7792026b8390398a8449ae8a812
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface AssignableQuantity {
      id?: unknown
      qty_available: number
    }
  }
}
