// TypesFromSerializers CacheKey 5d35ccdc86093a6059193bd71c483c89
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AssignableSingle.d {
  id?: unknown
}

