// TypesFromSerializers CacheKey 8a345dd95e9c70bf5bb35832cb281b3e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface AssignableSingle {
      id: number
      name: string
    }
  }
}
