// TypesFromSerializers CacheKey a6ff43e00d2f4711ca5b6746c1e87431
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type LocationsBasic from './Basic'

declare global {
  namespace Schema {
    interface LocationsBasic {
      id: number
      created_at: string | Date
      currency?: string
      name: string
      parent: LocationsBasic
      parent_id?: number
      slug: string
      updated_at: string | Date
    }
  }
}
