// TypesFromSerializers CacheKey cb11032b075050c818287a973579345f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface LocationsCounts {
      id?: number
      slug?: string
      counts: {
    items: number
    accessories: number
    consumables: number
    components: number
    licenses: number
    people: number
  }
      currency?: string
      name: string
      parent_id?: number
    }
  }
}
