// TypesFromSerializers CacheKey 4ee03685de5bdbcd3474bf70427a563b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface LocationsEdit {
      id: number
      currency?: string
      name: string
      parent_id?: number
      slug: string
    }
  }
}
