// TypesFromSerializers CacheKey 717d0f60ce7c61c4c11183ab6926cc36
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type LocationsOptions from './Options'

declare global {
  namespace Schema {
    interface LocationsEdit {
      id: unknown
      parent: LocationsOptions
      slug: unknown
    }
  }
}
