// TypesFromSerializers CacheKey 3ac681bd799cd2473c2fb74763d6ae81
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type LocationsOptions from './Options'

declare global {
  namespace Schema {
    interface LocationsEdit {
      id: number
      currency?: string
      name: string
      parent: LocationsOptions
      parent_id?: number
      slug: string
    }
  }
}
