// TypesFromSerializers CacheKey 92d731520b21676fff7af8b36dfd1117
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface LocationsFormData {
      id?: number
      slug?: string
      currency?: string
      name: string
      parent_id?: number
    }
  }
}
