// TypesFromSerializers CacheKey 12d4cf594e7695eca3ab8a8c51ad3fb1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type LocationsOptions from './Options'

declare global {
  namespace Schema {
    interface LocationsFormData {
      id?: number
      slug?: string
      currency?: string
      name: string
      parent?: LocationsOptions
      parent_id?: number
    }
  }
}
