// TypesFromSerializers CacheKey 1c3a70d8d83bf271f7a7cb95119e63fa
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ContactsBasic from '../Contacts/Basic'
import type DepartmentsBasic from '../Departments/Basic'
import type LocationsBasic from './Basic'

declare global {
  namespace Schema {
    interface LocationsIndex {
      id: number
      contact: ContactsBasic
      counts: {
    items: number
    accessories: number
    consumables: number
    components: number
    licenses: number
    people: number
  }
      created_at: string | Date
      currency?: string
      department: DepartmentsBasic
      location: LocationsBasic
      name: string
      parent: LocationsBasic
      parent_id?: number
      slug: string
      updated_at: string | Date
    }
  }
}
