// TypesFromSerializers CacheKey 2165f7e12fb669c6db17963f1b832d92
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Contact from '../Contact'
import type Department from '../Department'
import type Location from '../Location'

export default interface LocationsIndex {
  id?: number
  slug?: string
  contact: Contact
  counts: unknown
  createdAt: string | Date
  currency?: string
  department: Department
  location: Location
  name: string
  parent: Location
  parentId?: number
  updatedAt: string | Date
}

