// TypesFromSerializers CacheKey 8c16989a2e1568dd9d80c0ac58baf68e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Contact from '../Contact'
import type Department from '../Department'
import type Location from '../Location'

declare global {
  namespace Schema {
    interface LocationsIndex {
      id: number
      slug?: string
      contact: Contact
      counts: {
    items: number
    accessories: number
    consumables: number
    components: number
    licenses: number
    people: number
  }
      created_at: string | Date
      currency?: string
      department: Department
      location: Location
      name: string
      parent: Location
      parent_id?: number
      updated_at: string | Date
    }
  }
}
