// TypesFromSerializers CacheKey 44f5970d0c2162205d765fe2d5debeba
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface LocationsNew {
			id?: number
			slug?: string
			currency?: string
			name: string
			parent_id?: number
		}

	}
}
