// TypesFromSerializers CacheKey 37d8e8b5eb3d93aa737afa7741f879d2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface LocationsOptions {
      id: number
      slug?: string
      name: string
    }
  }
}
