// TypesFromSerializers CacheKey 58a0ddff345350e56a0a6d167a1e443c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface LocationsOptions {
  id?: number
  slug?: string
  name: string
}

