// TypesFromSerializers CacheKey fe8ff3f987232e6b4c3716e780e3a0cb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Activity from '../Activity'
import type Contact from '../Contact'
import type Department from '../Department'
import type Location from '../Location'

declare global {
  namespace Schema {
    interface LocationsShow {
      id: number
      activities: Activity[]
      contact: Contact
      counts: {
    items: number
    accessories: number
    consumables: number
    components: number
    licenses: number
    people: number
  }
      created_at: string | Date
      currency?: string
      department: Department
      name: string
      parent: Location
      parent_id?: number
      slug: string
      updated_at: string | Date
    }
  }
}
