// TypesFromSerializers CacheKey 5c7b5acecfad9b293306cccbf8cdc5a5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Activity } from '../Activity'
import type { Contact } from '../Contact'
import type { Department } from '../Department'
import type { Location } from '../Location'

declare global {
	 declare namespace Schema {
		export interface LocationsShow {
			id?: number
			slug?: string
			activities: Activity[]
			contact: Contact
			createdAt: string | Date
			currency?: string
			department: Department
			location: Location
			name: string
			parent: Location
			parentId?: number
			updatedAt: string | Date
		}

	}
}
