// TypesFromSerializers CacheKey 4875c75caecfc1fc7394ebd1e01f18e0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IpLeasesBasic from '../IpLeases/Basic'

declare global {
  namespace Schema {
    interface NicsBasic {
      id: number
      created_at: string | Date
      ips: IpLeasesBasic[]
      item_id: number
      mac?: unknown
      nic_type: "ethernet" | "wifi" | "fiber" | "cellular"
      updated_at: string | Date
    }
  }
}
