// TypesFromSerializers CacheKey e5538be19b345ad722c05a5e139c682b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IpLeasesBasic from '../IpLeases/Basic'

declare global {
  namespace Schema {
    interface NicsBasic {
      id: number
      created_at: string | Date
      ips: IpLeasesBasic[]
      item_id: number
      mac?: unknown
      nic_type: number
      updated_at: string | Date
    }
  }
}
