version: '3.9'
services:
  db:
    image: postgres:15.1-alpine 
    environment:
      POSTGRES_USER: "${PG_USERNAME}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    command: >
      bash -c "bin/docker-entrypoint"
    volumes:
      - .:/inventory
      - files:/inventory/storage
    ports:
      - "${SERVER_PORT}:3000"
    depends_on:
      - db
    environment:
      RACK_ENV: "production"
      RAILS_ENV: "production"
      NODE_ENV: "production"
      POSTGRES_USER: "${PG_USERNAME}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_HOST: postgres
    env_file: .env
    restart: always

volumes:
  postgres:
  files:
