version: '3.9'

services:
  db:
    image: postgres:15.4-alpine 
    environment:
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  web:
    image: inventory
    build: .
    command: >
      bash -c "bin/docker-entrypoint"
    volumes:
      - .:/inventory
      - files:/inventory/storage
      - secrets:/inventory/config/secrets
    ports:
      - "80:3000"
    depends_on:
      - db
    environment:
      RACK_ENV: "production"
      RAILS_ENV: "production"
      NODE_ENV: "production"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: postgres

volumes:
  postgres:
  files:
  secrets:
