// TypesFromSerializers CacheKey 8b3eea31701980fc8fb07cfa38263426
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface VendorsBasic {
      id: number
      created_at: string | Date
      name: string
      slug: string
      updated_at: string | Date
      url?: string
    }
  }
}
