// TypesFromSerializers CacheKey 3e67451895b4ebad1e244a531f09599d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface VendorsEdit {
      id: number
      name: string
      slug: string
      url?: string
    }
  }
}
