// TypesFromSerializers CacheKey cb214f14a6b6a82258ddaa7da2b6d66b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface VendorsFormData {
			id: number
			slug?: string
			name: string
			url?: string
		}

	}
}
