// TypesFromSerializers CacheKey 52eada57c59328d73adaecd533d502d8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface VendorsFormData {
			id?: number
			slug?: string
			name: string
			url?: string
		}

	}
}
