// TypesFromSerializers CacheKey 5a6f53edacf5a0062cfd43f3d1225f85
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Accessory from '../Accessory'
import type Activity from '../Activity'
import type Component from '../Component'
import type Consumable from '../Consumable'
import type Contact from '../Contact'
import type Contract from '../Contract'
import type Item from '../Item'

export default interface VendorsIndex {
  id: number
  slug?: string
  accessories: Accessory[]
  activities: Activity[]
  components: Component[]
  consumables: Consumable[]
  contact: Contact
  contracts: Contract[]
  createdAt: string | Date
  items: Item[]
  name: string
  updatedAt: string | Date
  url?: string
}

