// TypesFromSerializers CacheKey 501812c3c638d480c16e6a7d050fd30d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Accessory } from '../Accessory'
import type { Activity } from '../Activity'
import type { Component } from '../Component'
import type { Consumable } from '../Consumable'
import type { Contact } from '../Contact'
import type { Contract } from '../Contract'
import type { Item } from '../Item'

declare export global {
	declare namespace Schema {
		export interface VendorsIndex {
			id: number
			accessories: Accessory[]
			activities: Activity[]
			components: Component[]
			consumables: Consumable[]
			contact: Contact
			contracts: Contract[]
			created_at: string | Date
			items: Item[]
			name: string
			slug: string
			updated_at: string | Date
			url?: string
		}

	}
}
