// TypesFromSerializers CacheKey f60b0dd6da86765eb1c61f4caffefc2f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface VendorsNew {
  id: number
  slug?: string
  name: string
  url?: string
}

