// TypesFromSerializers CacheKey 1d93d84124356bdbbd0e1e5211fd184e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface VendorsOptions {
      id: number
      name: string
      slug: string
    }
  }
}
