// TypesFromSerializers CacheKey ea114877452b803047bb0edb0707a5e1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface VendorsOptions {
  id: number
  name: string
}

