// TypesFromSerializers CacheKey 7d0a992ae70f344b8a7ff205ee2790ee
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Accessory from '../Accessory'
import type Activity from '../Activity'
import type Component from '../Component'
import type Consumable from '../Consumable'
import type Contact from '../Contact'
import type Contract from '../Contract'
import type Item from '../Item'

declare global {
  namespace Schema {
    interface VendorsShow {
      id: number
      accessories: Accessory[]
      activities: Activity[]
      components: Component[]
      consumables: Consumable[]
      contact: Contact
      contracts: Contract[]
      counts: {
    items: number
    accessories: number
    consumables: number
    components: number
    licenses: number
    contracts: number
  }
      created_at: string | Date
      items: Item[]
      name: string
      slug: string
      updated_at: string | Date
      url?: string
    }
  }
}
