// TypesFromSerializers CacheKey 1b695667ba17c0dfafeb0ebc78dae84d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface NetworksEdit {
			id?: number
			address?: string
			dhcp_end?: string
			dhcp_start?: string
			gateway?: string
			name?: string
			notes?: string
			vlan_id?: number
		}

	}
}
