// TypesFromSerializers CacheKey 620744cb85cfdffe47560d7770986585
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface NetworksEdit {
      id: number
      address: string
      dhcp_end: string
      dhcp_start: string
      gateway: string
      name: string
      notes?: string
      vlan_id?: number
    }
  }
}
