// TypesFromSerializers CacheKey 91656d3948035be2808fd744560b37c1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface NetworksFormData {
			id?: number
			address?: string
			dhcp_end?: string
			dhcp_start?: string
			gateway?: string
			name?: string
			notes?: string
			vlan_id?: number
		}

	}
}
