// TypesFromSerializers CacheKey e3b5eed6e06fe1805fa47ed4ffb11f1f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface NetworksFormData {
      id?: number
      address: string
      broadcast: unknown
      dhcp_end?: string
      dhcp_start?: string
      gateway?: string
      name: string
      notes?: string
      vlan_id?: number
    }
  }
}
