// TypesFromSerializers CacheKey b65c281f6ef967eeefdf3c07a6d683e8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface NetworksIndex {
			id?: number
			address?: string
			broadcast: unknown
			createdAt: string | Date
			dhcpEnd?: string
			dhcpStart?: string
			gateway?: string
			name?: string
			notes?: string
			updatedAt: string | Date
			vlanId?: number
		}

	}
}
