// TypesFromSerializers CacheKey 36486934c66c6f4103f82acef955142b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface NetworksIndex {
  id?: number
  address?: unknown
  broadcast: unknown
  createdAt: string | Date
  dhcpEnd?: unknown
  dhcpStart?: unknown
  gateway?: unknown
  name?: string
  notes?: string
  updatedAt: string | Date
  vlanId?: number
}

