// TypesFromSerializers CacheKey 27d28713656fe106b960f829382ba9c8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface NetworksIndex {
      id: number
      address: string
      broadcast: string
      created_at: string | Date
      dhcp_end: string
      dhcp_start: string
      gateway: string
      name: string
      notes?: string
      updated_at: string | Date
      vlan_id?: number
    }
  }
}
