// TypesFromSerializers CacheKey 43ee6babd6238e8a0f87fc561c72b86d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface NetworksNew {
  id?: number
  address?: unknown
  dhcpEnd?: unknown
  dhcpStart?: unknown
  gateway?: unknown
  name?: string
  notes?: string
  vlanId?: number
}

