// TypesFromSerializers CacheKey f6406470b08e1f86b03db23f9e03b632
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface NetworksShow {
      id: number
      address: string
      broadcast: unknown
      created_at: string | Date
      dhcp_end?: string
      dhcp_start?: string
      gateway?: string
      hosts: string[]
      name: string
      notes?: string
      page: number
      updated_at: string | Date
      vlan_id?: number
    }
  }
}
