// TypesFromSerializers CacheKey cd921a8e0f88017cdb43a53e49395836
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface NetworksShow {
			id?: number
			address?: string
			broadcast: string
			createdAt: string | Date
			dhcpEnd?: string
			dhcpStart?: string
			gateway?: string
			hosts: string[]
			name?: string
			notes?: string
			page: number
			updatedAt: string | Date
			vlanId?: number
		}

	}
}
