// TypesFromSerializers CacheKey b9a831d6ff3afbdbb316c44d3eb50f8e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface NetworksShow {
  id?: number
  address?: unknown
  broadcast: unknown
  createdAt: string | Date
  dhcpEnd?: unknown
  dhcpStart?: unknown
  gateway?: unknown
  hosts: unknown
  name?: string
  notes?: string
  updatedAt: string | Date
  vlanId?: number
}

