// TypesFromSerializers CacheKey 004738cd2e16dca875a22f5bef98b30a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface NetworksShow {
  id?: number
  address?: unknown
  broadcast: unknown
  createdAt: string | Date
  dhcpEnd?: unknown
  dhcpStart?: unknown
  gateway?: unknown
  hosts: unknown
  name?: string
  notes?: string
  page: unknown
  updatedAt: string | Date
  vlanId?: number
}

