// TypesFromSerializers CacheKey e36b778d97c6b09876d0b883c8fa65c2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface NetworksShow {
			id: number
			address?: string
			broadcast: string
			created_at: string | Date
			dhcp_end: string
			dhcp_start: string
			gateway: string
			hosts: string[]
			name?: string
			notes?: string
			page: number
			updated_at: string | Date
			vlan_id?: number
		}

	}
}
