// TypesFromSerializers CacheKey 6a8c776dd118fc9f8e7e20e937093220
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface NetworksSpotlight {
      id: string
      address: string
      name: string
      notes?: string
      vlan_id?: number
    }
  }
}
