// TypesFromSerializers CacheKey 89de652573e30843be8c2be5874f828e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface NetworksSpotlight {
      id: string
      address: string
      name: string
      notes?: string
      vlan_id?: number
    }
  }
}
