// TypesFromSerializers CacheKey b8cd788e0b40134627f96e8e279666fd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Activity from './Activity'
import type Assignment from './Assignment'
import type Category from './Category'
import type Location from './Location'
import type Department from './Department'
import type Manufacturer from './Manufacturer'
import type Model from './Model'
import type Purchase from './Purchase'
import type Vendor from './Vendor'

declare global {
  namespace Schema {
    interface Accessory {
      id: number
      activities: Activity[]
      asset_tag?: string
      assignments: Assignment[]
      category: Category
      cost: number
      cost_currency: string
      created_at: string | Date
      default_location: Location
      default_location_id?: number
      department: Department
      manufacturer: Manufacturer
      min_qty?: number
      model: Model
      model_id: number
      name: string
      notes?: string
      purchase: Purchase
      qty?: number
      qty_available: number
      requestable: boolean
      serial?: string
      updated_at: string | Date
      vendor: Vendor
      vendor_id?: number
    }
  }
}
