// TypesFromSerializers CacheKey 0e140f47370b02816534923a510bc799
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface Activity {
			id?: unknown
			createdAt: unknown
			key: unknown
			ownerId: unknown
			ownerType: unknown
			parameters: unknown
			recipientId: unknown
			recipientType: unknown
			trackableId: unknown
			trackableType: unknown
			updatedAt: unknown
		}

	}
}
