// TypesFromSerializers CacheKey 0d8fe4475e0940204ab854e607991e4a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface Activity {
			id?: unknown
			created_at: unknown
			key: unknown
			owner_id: unknown
			owner_type: unknown
			parameters: unknown
			recipient_id: unknown
			recipient_type: unknown
			trackable_id: unknown
			trackable_type: unknown
			updated_at: unknown
		}

	}
}
