// TypesFromSerializers CacheKey f33304d19722edc19fdbb3db46bf80bf
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Activity {
      id: number
      created_at: string | Date
      key?: string
      owner_id?: number
      owner_type?: string
      parameters: unknown
      recipient_id?: number
      recipient_type?: string
      trackable_id?: number
      trackable_type?: string
      updated_at: string | Date
    }
  }
}
