// TypesFromSerializers CacheKey c526211f1fbd585eb0d0082119ca6860
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Asset {
      id?: number
      asset_tag?: string
      available_to_checkout: unknown
      cost: number
      cost_currency: string
      default_location_id?: number
      min_qty?: number
      model_id: number
      name: string
      notes?: string
      purchased_at?: string | Date
      qty?: number
      requestable: boolean
      serial?: string
      status_label_id?: number
      type: string
      vendor_id?: number
    }
  }
}
