// TypesFromSerializers CacheKey af0a9d40d98e8b77f50776e659df92e2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Assignable {
      id: number
      name: string
    }
  }
}
