// TypesFromSerializers CacheKey 269662ec2fa2809d2ac27a125f0c6072
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Proc:0x000000010f2978f8 from '../Proc:0x000000010f2978f8'
import type Proc:0x000000010f297790 from '../Proc:0x000000010f297790'

export default interface Assignment {
  id?: number
  active: boolean
  assignToable: #<Proc:0x000000010f2978f8 /Users/avram/Development/ruby/inventory/app/serializers/assignment_serializer.rb:20 (lambda)>
  assignToableId: number
  assignToableType: string
  assignable: #<Proc:0x000000010f297790 /Users/avram/Development/ruby/inventory/app/serializers/assignment_serializer.rb:21 (lambda)>
  assignableId: number
  assignableType: string
  assignedAt?: string | Date
  createdAt: string | Date
  createdById?: number
  expectedAt?: string | Date
  locationId: number
  notes?: string
  qty: number
  returnedAt?: string | Date
  status?: number
  updatedAt: string | Date
}

