// TypesFromSerializers CacheKey ac1c3acc47421900eea88ceb65af43eb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Assignable {
      id: number
      created_at: unknown
      name: string
      updated_at: unknown
    }
  }
}
