// TypesFromSerializers CacheKey dba9a73098ab991e7ec67ca0c5201ad5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { AssignToable } from './AssignToable'
import type { Assignable } from './Assignable'

declare export global {
	declare namespace Schema {
		export interface Assignment {
			id?: number
			active: boolean
			assign_toable: AssignToable
			assign_toable_id: number
			assign_toable_type: TAssignToable
			assignable: Assignable
			assignable_id: number
			assignable_type: TAssignable
			assigned_at?: string | Date
			created_at: string | Date
			created_by_id?: number
			expected_at?: string | Date
			location_id: number
			notes?: string
			qty: number
			returned_at?: string | Date
			status?: number
			updated_at: string | Date
		}

	}
}
