// TypesFromSerializers CacheKey 948af169260cfccd73d628ca574b2326
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Assignable {
      id: number
      name: string
    }
  }
}
