// TypesFromSerializers CacheKey 367864d1e4828adb04dda78210d0d17e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface AssignToable {
      id: number
      name: string
    }
  }
}
