// TypesFromSerializers CacheKey a631b2cad0332af827ea12c809f9af1c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface AssignToable {
      id: number
      created_at: string|Date
      name: string
      updated_at: string|Date
    }
  }
}
