// TypesFromSerializers CacheKey e067a01acff428c31d99f8e8f0a40433
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface Category {
			id?: number
			categorizable_type: string
			created_at: string | Date
			description?: string
			name?: string
			slug: string
			updated_at: string | Date
		}

	}
}
