// TypesFromSerializers CacheKey 5ef74cbd79e384256c11c397ea7370da
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Category {
  id?: number
  categorizableType: string
  createdAt: string | Date
  description?: string
  name?: string
  slug: string
  updatedAt: string | Date
}

