// TypesFromSerializers CacheKey 0a6bd9a00d4fb3fdd6bd2af63c2c7545
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Category.d {
  id?: number
  categorizableType: string
  createdAt: string | Date
  description?: string
  name?: string
  slug: string
  updatedAt: string | Date
}

