// TypesFromSerializers CacheKey 74f2909f92b00d0fa889209b2592d4c1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface Company {
			id?: number
			createdAt: string | Date
			name: string
			settings: unknown
			slug: string
			updatedAt: string | Date
		}

	}
}
