// TypesFromSerializers CacheKey 29777b22f5e5b3e891c92f899a33d5f9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Company {
      id?: number
      created_at: string | Date
      default_currency: string
      name: string
      settings: Record<string, string>
      slug: string
      updated_at: string | Date
    }
  }
}
