// TypesFromSerializers CacheKey 5ef74fabc7254e12e6f4f3e7d21a4eb5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface Component {
			id?: unknown
			asset_tag: unknown
			cost: number
			cost_currency: unknown
			created_at: unknown
			default_location_id: unknown
			min_qty: unknown
			model_id: unknown
			name: unknown
			notes: unknown
			purchased_at: unknown
			qty: unknown
			qty_available: number
			serial: unknown
			updated_at: unknown
			vendor_id: unknown
		}

	}
}
