// TypesFromSerializers CacheKey 58042f2463c10c520d324185f01ec76a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface Company {
			id?: number
			created_at: string | Date
			name: string
			settings: unknown
			slug: string
			updated_at: string | Date
		}

	}
}
