// TypesFromSerializers CacheKey aeed19021d8b27a0304b63f98105066b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../Money'

declare global {
  namespace Schema {
    interface Consumable {
      id: number
      cost: Money
      cost_currency: string
      default_location_id?: number
      min_qty?: number
      model_id: number
      name: string
      notes?: string
      qty?: number
      qty_available: number
      requestable: boolean
      vendor_id?: number
    }
  }
}
