// TypesFromSerializers CacheKey ff024a3d4c7d4a9ac39ef2d895431f74
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../Money'

declare global {
  namespace Schema {
    interface Consumable {
      id: number
      cost: Money
      cost_currency: string
      default_location_id?: number
      min_qty?: number
      model_id: number
      name: string
      notes?: string
      qty?: number
      qty_available: number
      requestable: boolean
      vendor_id?: number
    }
  }
}
