// TypesFromSerializers CacheKey f1db749eb52d3f6bf32e5ab5810fe3f5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Contract {
  id?: number
  beginsAt?: string | Date
  categoryId: number
  createdAt: string | Date
  endsAt?: string | Date
  name: string
  notes?: string
  number?: string
  updatedAt: string | Date
  vendorId: number
}

