// TypesFromSerializers CacheKey 7640d89988b4c8140afa51cefe75d249
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Address from './Address'
import type Email from './Email'
import type Phone from './Phone'
import type Website from './Website'

export default interface Contact {
  id?: number
  addresses: Address[]
  contactableId?: number
  contactableType?: string
  createdAt: string | Date
  emails: Email[]
  notes?: string
  phones: Phone[]
  primaryAddressId?: number
  primaryEmailId?: number
  primaryPhoneId?: number
  updatedAt: string | Date
  websites: Website[]
}

