// TypesFromSerializers CacheKey 2894d3b38f55c9b84d0fa28d3f2c14e4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from './Categories/Options'

declare global {
  namespace Schema {
    interface Contract {
      id?: number
      slug?: string
      begins_at?: string | Date
      category?: CategoriesOptions
      category_id: number
      ends_at?: string | Date
      name: string
      notes?: string
      number?: string
      vendor_id: number
    }
  }
}
