// TypesFromSerializers CacheKey d608d497b340e3f6db4982e8372294f0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface Department {
			id?: number
			created_at: string | Date
			location_id?: number
			name?: string
			notes?: string
			slug: string
			updated_at: string | Date
		}

	}
}
