// TypesFromSerializers CacheKey 400ffc08531a551cc635392497e2cafb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Department {
      id: number
      created_at: string | Date
      location_id?: number
      name?: string
      notes?: string
      slug: string
      updated_at: string | Date
    }
  }
}
