// TypesFromSerializers CacheKey d10adc01ca1dec6ca0ea74aa8bf687ff
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Department {
      id: number
      created_at: string | Date
      location_id?: number
      name: string
      notes?: string
      slug: string
      updated_at: string | Date
    }
  }
}
