// TypesFromSerializers CacheKey e8e5afc2501deda665d6303ab5e643ce
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Department {
  id?: number
  createdAt: string | Date
  locationId?: number
  name?: string
  notes?: string
  slug: string
  updatedAt: string | Date
}

