// TypesFromSerializers CacheKey 497e8b0d7fd9b87a39cead945ff87809
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from './Categories/Options'

declare global {
  namespace Schema {
    interface Documentation {
      id?: number
      slug?: string
      body?: string
      category: CategoriesOptions
      category_id: number
      created_by_id?: number
      documentable_id: number
      documentable_name: string
      documentable_type: string
      title: string
    }
  }
}
