// TypesFromSerializers CacheKey c941ab670328b9d1b79bb097ffd8219c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Documentable {
      id: unknown
      created_at: unknown
      name: string
      updated_at: unknown
    }
  }
}
