// TypesFromSerializers CacheKey 981f0a2bb88c64262b11226247e53adc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Documentation {
      id?: number
      body?: string
      created_at: string | Date
      slug: string
      title?: string
      updated_at: string | Date
    }
  }
}
