// TypesFromSerializers CacheKey ef054ca2e4b6a000de14a4b0367fdb94
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from './Category'
import type Contact from './Contact'

export default interface Email {
  id?: number
  category: Category
  categoryId?: number
  contact: Contact
  contactId: number
  createdAt: string | Date
  email?: string
  notes?: string
  updatedAt: string | Date
}

