// TypesFromSerializers CacheKey 2dd0ebfef60a42aacc51a24789e6baad
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from './Categories/Options'
import type Contact from './Contact'

declare global {
  namespace Schema {
    interface Email {
      id?: number
      category: CategoriesOptions
      category_id?: number
      contact: Contact
      contact_id: number
      email: string
      notes?: string
    }
  }
}
