// TypesFromSerializers CacheKey f854e0d90deb9646869bf8ced06ef3e5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from './Category'
import type Contact from './Contact'

declare global {
  namespace Schema {
    interface Email {
      id?: number
      category: Category
      category_id?: number
      contact: Contact
      contact_id: number
      created_at: string | Date
      email: string
      notes?: string
      updated_at: string | Date
    }
  }
}
