// TypesFromSerializers CacheKey 7fccbfadd0f504c5e8e5ea365686ac3f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IpLease {
      id?: number
      active: boolean
      address?: string
    }
  }
}
