// TypesFromSerializers CacheKey b3bb31563f27a0981a3714ca0355bd0d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface IpLease {
			id?: number
			active: boolean
			address?: string
			created_at: string | Date
			updated_at: string | Date
		}

	}
}
