// TypesFromSerializers CacheKey 7cdb6d1fdffd34f3c3070a4f0b09a870
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IpLease {
  id?: number
  active: boolean
  address?: unknown
  createdAt: string | Date
  updatedAt: string | Date
}

