// TypesFromSerializers CacheKey 7063d4cd7ef0b0271572f1460f718043
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IpLease {
      id?: number
      active: boolean
      address?: string
    }
  }
}
