// TypesFromSerializers CacheKey bc87642197e7f6b9392c16cd5e888eb3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Item {
      id: number
      asset_tag?: string
      assigned: boolean
      cost: number
      cost_currency: string
      created_at: string | Date
      default_location_id?: number
      model_id: number
      name: string
      notes?: string
      purchased_at?: string | Date
      requestable: boolean
      serial?: string
      updated_at: string | Date
      vendor_id?: number
    }
  }
}
