// TypesFromSerializers CacheKey 8996536b6e141e280131f8133147a468
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface Item {
			id?: number
			assetTag?: string
			assigned: unknown
			cost: unknown
			costCurrency: string
			createdAt: string | Date
			defaultLocationId?: number
			modelId: number
			name: string
			notes?: string
			purchasedAt?: string | Date
			requestable: boolean
			serial?: string
			updatedAt: string | Date
			vendorId?: number
		}

	}
}
