// TypesFromSerializers CacheKey 0dde2fc50c989df673b38093c4cd5c57
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface Item {
			id?: number
			asset_tag?: string
			assigned: unknown
			cost: number
			cost_currency: string
			created_at: string | Date
			default_location_id?: number
			model_id: number
			name: string
			notes?: string
			purchased_at?: string | Date
			requestable: boolean
			serial?: string
			updated_at: string | Date
			vendor_id?: number
		}

	}
}
