// TypesFromSerializers CacheKey d5c870b1020c40b25b2172501047c947
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface License {
      id: number
      category_id: number
      cost: number
      cost_currency: string
      created_at: string | Date
      expires_at?: string | Date
      key?: string
      licenser_email?: string
      licenser_name?: string
      maintained: boolean
      manufacturer_id: number
      name: string
      notes?: string
      purchased_at?: string | Date
      qty?: number
      qty_available: number
      reassignable: boolean
      status_label_id?: number
      terminates_at?: string | Date
      updated_at: string | Date
      vendor_id?: number
    }
  }
}
