// TypesFromSerializers CacheKey b3c8d4fc5c94cb995e83b04533df8391
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface License {
			id?: number
			category_id: number
			cost: unknown
			cost_currency: string
			created_at: string | Date
			expires_at?: string | Date
			key?: string
			licenser_email?: string
			licenser_name?: string
			maintained: boolean
			manufacturer_id: number
			name: string
			notes?: string
			purchased_at?: string | Date
			qty?: number
			qty_available: unknown
			reassignable: boolean
			terminates_at?: string | Date
			updated_at: string | Date
			vendor_id?: number
		}

	}
}
