// TypesFromSerializers CacheKey 7f44637571bbfa84ea15f8d771281610
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Location {
      id?: number
      slug?: string
      currency?: string
      name: string
      parent_id?: number
    }
  }
}
