// TypesFromSerializers CacheKey 60543dc9f266997fbc6c548f71be4f27
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Location.d {
  id?: number
  slug?: string
  createdAt: string | Date
  currency?: string
  name: string
  parentId?: number
  updatedAt: string | Date
}

