// TypesFromSerializers CacheKey ec109daafd9eb761af7dcf62a40377e0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface Location {
			id?: number
			slug?: string
			createdAt: string | Date
			currency?: string
			name: string
			parentId?: number
			updatedAt: string | Date
		}

	}
}
