// TypesFromSerializers CacheKey 6b65588d10946520f5b00cf218fb63c9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Manufacturer {
      id: number
      created_at: string | Date
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
