// TypesFromSerializers CacheKey 91d98011b2708fdcfc34ecb027d9a7eb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface Manufacturer {
			id: number
			slug?: string
			created_at: string | Date
			name?: string
			updated_at: string | Date
		}

	}
}
