// TypesFromSerializers CacheKey 9fef09d46176daa830eff7581b010428
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Manufacturer {
  id: number
  slug?: string
  createdAt: string | Date
  name?: string
  updatedAt: string | Date
}

