// TypesFromSerializers CacheKey 2460c6b1868c23068b829ebfc4accf0f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface Model {
			id?: number
			categoryId: number
			createdAt: string | Date
			manufacturerId: number
			modelNumber?: string
			name?: string
			notes?: string
			slug: string
			updatedAt: string | Date
		}

	}
}
