// TypesFromSerializers CacheKey 70d59109a71539c1d62f815977aa3643
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Model.d {
  id?: number
  categoryId: number
  createdAt: string | Date
  manufacturerId: number
  modelNumber?: string
  name?: string
  notes?: string
  slug: string
  updatedAt: string | Date
}

