// TypesFromSerializers CacheKey 65d7fa3f52553d7b3f17f15082986874
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Network {
      id?: number
      address?: string
      broadcast: unknown
      created_at: string | Date
      dhcp_end?: string
      dhcp_start?: string
      gateway?: string
      name?: string
      notes?: string
      updated_at: string | Date
      vlan_id?: number
    }
  }
}
