// TypesFromSerializers CacheKey 8ed0899bfe5cfa6cbfd75d5a500bf08a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Network {
      id?: number
      address: string
      dhcp_end: string
      dhcp_start: string
      gateway: string
      name: string
      notes?: string
      vlan_id?: number
    }
  }
}
