// TypesFromSerializers CacheKey 9d2502da24d9fbb83a1b91b0403344b2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Network {
      id?: number
      address: string
      broadcast: unknown
      created_at: string | Date
      dhcp_end?: string
      dhcp_start?: string
      gateway?: string
      name: string
      notes?: string
      updated_at: string | Date
      vlan_id?: number
    }
  }
}
