// TypesFromSerializers CacheKey c1d1c3fa9a1fd41797ebcdf4a5b6bbbb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Nic {
      id?: number
      item_id: number
      mac?: unknown
      nic_type: "ethernet" | "wifi" | "fiber" | "cellular"
    }
  }
}
