// TypesFromSerializers CacheKey e14efef0e212fda8ba6cc80b7320d93d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { IpLease } from './IpLease'

declare export global {
	declare namespace Schema {
		export interface Nic {
			id?: number
			created_at: string | Date
			ips: IpLease[]
			item_id: number
			mac?: unknown
			nic_type: number
			updated_at: string | Date
		}

	}
}
