// TypesFromSerializers CacheKey c1a84a309065d5f6ced02a8b32c49cde
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Order {
      id?: number
      canceled_at?: string | Date
      canceled_reason?: string
      delivered_at?: string | Date
      discount_cents?: number
      discount_currency: string
      discount_decription?: string
      expected_at?: string | Date
      notes?: string
      number?: string
      ordered_at?: string | Date
      returned_at?: string | Date
      returned_reason?: string
      shipping_cents?: number
      shipping_currency: string
      submitted_at?: string | Date
      tax_cents?: number
      tax_currency: string
      user_id: number
      vendor_id: number
    }
  }
}
