// TypesFromSerializers CacheKey e8ce9b6dda2604b01be15a0a4ae55d65
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Ownership {
  id?: number
  companyId: number
  departmentId?: number
}

