// TypesFromSerializers CacheKey 7ff65c0b678510f8e0a8c92a8499f5bf
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Ownership {
      id?: number
      company_id: number
      department_id?: number
    }
  }
}
