// TypesFromSerializers CacheKey a874a47562b2bcfab3ca66e8b49e548d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PersonGroup {
      id?: number
      slug?: string
      description?: string
      name: string
    }
  }
}
