// TypesFromSerializers CacheKey 1202d02c7358c25d5c85f8a407b9b779
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PersonGroup {
      id: number
      slug?: string
      created_at: string | Date
      description?: string
      name: string
      updated_at: string | Date
    }
  }
}
