// TypesFromSerializers CacheKey 05469d039062d28b712a9c9148402e3c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Person {
      id?: number
      active: boolean
      department_id: unknown
      employee_number?: string
      first_name: string
      job_title?: string
      last_name: string
      location_id?: number
      manager_id?: number
      middle_name?: string
      name: string
      user_id?: number
    }
  }
}
