// TypesFromSerializers CacheKey ca2bc9c1d9e2a3873a8b1cd473eddc6e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Person {
      id?: number
      active: boolean
      department_id: unknown
      employee_number?: string
      first_name: string
      job_title?: string
      last_name: string
      location_id?: number
      manager_id?: number
      middle_name?: string
      name: string
      user_id?: number
    }
  }
}
