// TypesFromSerializers CacheKey e6032de3245b12d34e4fa00c7ed57b6e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PersonGroup {
      id?: number
      slug?: string
      description?: string
      name: string
    }
  }
}
