// TypesFromSerializers CacheKey a2a1275e20aac4f24e51b84e2f896abd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface PersonGroup {
  id: number
  slug?: string
  createdAt: string | Date
  description?: string
  name?: string
  updatedAt: string | Date
}

