// TypesFromSerializers CacheKey 6270ec04edf0b7f8102775b03149c564
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from './Categories/Options'

declare global {
  namespace Schema {
    interface Phone {
      id?: number
      category: CategoriesOptions
      category_id: number
      contact_id: number
      created_at: string | Date
      extension?: string
      notes?: string
      number: string
      updated_at: string | Date
    }
  }
}
