// TypesFromSerializers CacheKey adbd4acfb324830076b78f0640e6f6bd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Activity } from './Activity'
import type { Category } from './Category'
import type { Contact } from './Contact'

declare global {
	 declare namespace Schema {
		export interface Phone {
			id?: number
			activities: Activity[]
			category: Category
			categoryId: number
			contact: Contact
			contactId: number
			createdAt: string | Date
			extension?: string
			notes?: string
			number: string
			updatedAt: string | Date
		}

	}
}
