// TypesFromSerializers CacheKey 7bc9e941d60c31deb5cf4577189352c9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Phone {
      id?: number
      category_id: number
      contact_id: number
      created_at: string | Date
      extension?: string
      notes?: string
      number: string
      updated_at: string | Date
    }
  }
}
