// TypesFromSerializers CacheKey 2e30cd357d66726c0e8d9f5d1587f64f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../Money'

declare global {
  namespace Schema {
    interface Purchase {
      id?: number
      cost: Money
      cost_currency: string
      notes?: string
      order_id?: number
      purchasable_id: number
      purchasable_type: string
      qty?: number
    }
  }
}
