// TypesFromSerializers CacheKey fcc2fef66e08e2bf48db8bde3e72d6e7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Accessory } from './Accessory'
import type { Activity } from './Activity'
import type { Company } from './Company'
import type { Component } from './Component'
import type { Consumable } from './Consumable'
import type { Department } from './Department'
import type { Item } from './Item'
import type { Order } from './Order'

declare global {
  namespace Schema {
    interface Purchase {
      id?: number
      accessory: Accessory
      activities: Activity[]
      company: Company
      component: Component
      consumable: Consumable
      cost: unknown
      cost_currency: string
      created_at: string | Date
      department: Department
      item: Item
      notes?: string
      order: Order
      order_id?: number
      purchasable_id: number
      purchasable_type: string
      qty?: number
      updated_at: string | Date
    }
  }
}
