// TypesFromSerializers CacheKey 88b983a39cc0ec1520052b5990d5e111
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Activity } from './Activity'
import type { Person } from './Person'
import type { PersonGroup } from './PersonGroup'

declare global {
	 declare namespace Schema {
		export interface Role {
			id?: number
			activities: Activity[]
			createdAt: string | Date
			name?: string
			people: Person[]
			personGroups: PersonGroup[]
			resourceId?: number
			resourceType?: string
			updatedAt: string | Date
		}

	}
}
