// TypesFromSerializers CacheKey 99b83836bd2dd02775fa0d6459ad771d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Search {
      id: unknown
      content: unknown
      created_at: unknown
      searchable_id: unknown
      searchable_type: unknown
      updated_at: unknown
    }
  }
}
