// TypesFromSerializers CacheKey cdb2c7af70548b9dbc5185206d1c66b1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Search {
      id?: number
      content?: string
      created_at: string | Date
      label?: string
      searchable_id?: number
      searchable_type?: string
      updated_at: string | Date
    }
  }
}
