// TypesFromSerializers CacheKey b33ea015cfd90a695872d271ce9ff3d5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Search {
      id?: number
      content?: string
      created_at: string | Date
      name: string
      searchable_id?: number
      searchable_type?: string
      updated_at: string | Date
    }
  }
}
