// TypesFromSerializers CacheKey 43c71b436c1650a67441c3cea107d891
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Smtp {
      id?: number
      address?: string
      created_at: string | Date
      domain?: string
      host: string
      name: string
      notes?: string
      password?: string
      port?: number
      security: number
      updated_at: string | Date
      username?: string
    }
  }
}
