// TypesFromSerializers CacheKey b88c90e47596f86d233f088632f0c66d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Accessory from './Accessory'
import type Component from './Component'
import type Consumable from './Consumable'
import type Contract from './Contract'
import type Item from './Item'
import type License from './License'
import type Network from './Network'
import type Person from './Person'
import type Ticket from './Ticket'
import type Vendor from './Vendor'

export default interface Spotlight {
  id?: unknown
  accessories: Accessory[]
  components: Component[]
  consumables: Consumable[]
  contracts: Contract[]
  items: Item[]
  licenses: License[]
  networks: Network[]
  people: Person[]
  tickets: Ticket[]
  vendors: Vendor[]
}

