// TypesFromSerializers CacheKey d4670caef62e1f1232e350968f968801
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface StatusLabel {
			id: number
			slug?: string
			createdAt: string | Date
			description?: string
			name?: string
			statusType: number
			updatedAt: string | Date
		}

	}
}
