// TypesFromSerializers CacheKey a9008d8b531ee479cf140094f5c8080d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface StatusLabel {
      id: number
      slug?: string
      created_at: string | Date
      description?: string
      name: string
      status_type: number
      updated_at: string | Date
    }
  }
}
