// TypesFromSerializers CacheKey 1c531b3b48460970b9aa92dfc9e9b8a0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface StatusLabel {
      id?: number
      slug?: string
      description?: string
      name: string
      status_type: number
    }
  }
}
