// TypesFromSerializers CacheKey 39682256dd090886f7cbf17c08bf9288
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface TicketStatus {
      id?: number
      created_at: string | Date
      name: string
      updated_at: string | Date
    }
  }
}
