// TypesFromSerializers CacheKey db1cab640fcdb327b9d7f011d787f1be
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Person } from './Person'

declare global {
	 declare namespace Schema {
		export interface TicketMessage {
			id?: number
			body?: string
			createdAt: string | Date
			createdBy: Person
			createdById?: number
			parentId?: number
			ticketId: number
			updatedAt: string | Date
		}

	}
}
