// TypesFromSerializers CacheKey 0e8f958d92cfda7c67392d6ef540bc19
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from './Person'

declare global {
  namespace Schema {
    interface TicketMessage {
      id?: number
      body: string
      created_at: string | Date
      created_by: Person
      created_by_id?: number
      parent_id?: number
      ticket_id: number
      updated_at: string | Date
    }
  }
}
