// TypesFromSerializers CacheKey 6fc0ba9a222df648e76e6f0862e961b0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Ticket {
      id?: number
      asset_id?: number
      created_by_id?: number
      description?: string
      number: number
      primary_contact_id?: number
      priority: "urgent" | "high" | "standard" | "low"
      status_id?: number
      subject: string
    }
  }
}
