// TypesFromSerializers CacheKey a8a0601cb1a412b5ac4fbcfa242d571e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface TicketAssignment {
			id?: number
			createdAt: string | Date
			personId: number
			ticketId: number
			updatedAt: string | Date
		}

	}
}
