// TypesFromSerializers CacheKey 63a614e9ebf5f40ad054261c83406236
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface TicketAssignment {
      id?: number
      person_id: number
      ticket_id: number
    }
  }
}
