// TypesFromSerializers CacheKey 23725483f640c96f2f8478b37098733e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface TicketAssignment {
			id?: number
			created_at: string | Date
			person_id: number
			ticket_id: number
			updated_at: string | Date
		}

	}
}
