// TypesFromSerializers CacheKey 59c61b7483d899829dec1ac7975cc22a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface TicketStatus {
      id?: number
      created_at: string | Date
      name?: string
      updated_at: string | Date
    }
  }
}
