// TypesFromSerializers CacheKey 2ef35592a6d02db58dfc9ea44d6e1ae0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface User {
      id?: number
      active: boolean
      email: string
    }
  }
}
