// TypesFromSerializers CacheKey 51fb7517f59e038275d1b6b8ce0c4a0d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Vendor.d {
  id: number
  slug?: string
  createdAt: string | Date
  name: string
  updatedAt: string | Date
  url?: string
}

