// TypesFromSerializers CacheKey 137b9c31ea1fecbfce86ea074f21f0a5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Vendor {
      id: number
      created_at: string | Date
      name: string
      slug: string
      updated_at: string | Date
      url?: string
    }
  }
}
