// TypesFromSerializers CacheKey 72ff1c40a2608a3656ccdfe07144e6ec
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface Vendor {
			id: number
			slug?: string
			createdAt: string | Date
			name: string
			updatedAt: string | Date
			url?: string
		}

	}
}
