// TypesFromSerializers CacheKey aaafc45aa7414847e0a0540dff3f4044
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Activity from './Activity'
import type Category from './Category'
import type Contact from './Contact'

declare global {
  namespace Schema {
    interface Website {
      id?: number
      activities: Activity[]
      category: Category
      contact: Contact
      contact_id: number
      created_at: string | Date
      name?: string
      notes?: string
      updated_at: string | Date
      url: string
    }
  }
}
