// TypesFromSerializers CacheKey 24b4d0c16c172a7d55c5d8c636362484
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'
import type Company from '../Company'
import type Manufacturer from '../Manufacturer'
import type Model from '../Model'
import type StatusLabel from '../StatusLabel'
import type Vendor from '../Vendor'

declare global {
  namespace Schema {
    interface ItemsBasic {
      id: number
      asset_tag?: string
      assigned: boolean
      category: Category
      company: Company
      cost: number
      cost_currency: string
      created_at: string | Date
      default_location_id?: number
      manufacturer: Manufacturer
      model: Model
      model_id: number
      name: string
      notes?: string
      purchased_at?: string | Date
      requestable: boolean
      serial?: string
      status_label: StatusLabel
      status_label_id?: number
      updated_at: string | Date
      vendor: Vendor
      vendor_id?: number
    }
  }
}
