// TypesFromSerializers CacheKey dd0d17126774a22388fd3706910fd021
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ItemsCheckout {
  id?: number
  assetTag?: string
  assigned: unknown
  cost: unknown
  costCurrency: string
  createdAt: string | Date
  defaultLocationId?: number
  modelId: number
  name: string
  notes?: string
  purchasedAt?: string | Date
  requestable: boolean
  serial?: string
  updatedAt: string | Date
  vendorId?: number
}

