// TypesFromSerializers CacheKey 16576663bf9cad500022f971181ff029
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type LocationsOptions from '../Locations/Options'
import type DepartmentsOptions from '../Departments/Options'
import type ModelsOptions from '../Models/Options'
import type StatusLabelsOptions from '../StatusLabels/Options'
import type VendorsOptions from '../Vendors/Options'

declare global {
  namespace Schema {
    interface ItemsEdit {
      id: number
      asset_tag?: string
      assigned: boolean
      cost: number
      cost_currency: string
      created_at: string | Date
      default_location?: LocationsOptions
      default_location_id?: number
      department?: DepartmentsOptions
      department_id: number
      model?: ModelsOptions
      model_id: number
      name: string
      notes?: string
      purchased_at?: string | Date
      requestable: boolean
      serial?: string
      status_label?: StatusLabelsOptions
      status_label_id?: number
      updated_at: string | Date
      vendor?: VendorsOptions
      vendor_id?: number
    }
  }
}
