// TypesFromSerializers CacheKey ab231ea1ddd657a83121cba38ed2f68d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface ItemsEdit {
			id?: number
			asset_tag?: string
			assigned: unknown
			cost: number
			cost_currency: string
			default_location_id?: number
			model_id: number
			name: string
			notes?: string
			purchased_at?: string | Date
			requestable: boolean
			serial?: string
			vendor_id?: number
		}

	}
}
