// TypesFromSerializers CacheKey b790b2913a0f0d12eb1315d2070ac6d9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type LocationsOptions from '../Locations/Options'
import type DepartmentsOptions from '../Departments/Options'
import type ModelsOptions from '../Models/Options'
import type VendorsOptions from '../Vendors/Options'

declare global {
  namespace Schema {
    interface ItemsEdit {
      id: number
      asset_tag?: string
      assigned: boolean
      cost: number
      cost_currency: string
      default_location: LocationsOptions
      default_location_id?: number
      department: DepartmentsOptions
      department_id: number
      model: ModelsOptions
      model_id: number
      name: string
      notes?: string
      purchased_at?: string | Date
      requestable: boolean
      serial?: string
      vendor: VendorsOptions
      vendor_id?: number
    }
  }
}
