// TypesFromSerializers CacheKey 3f2634f38ca42af7c994c362b9fb25f5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type LocationsOptions from '../Locations/Options'
import type DepartmentsOptions from '../Departments/Options'
import type ModelsOptions from '../Models/Options'
import type VendorsOptions from '../Vendors/Options'

declare global {
  namespace Schema {
    interface ItemsFormData {
      id: number
      asset_tag?: string
      cost: number
      cost_currency: string
      created_at: string | Date
      default_location?: LocationsOptions
      default_location_id?: number
      department: DepartmentsOptions
      department_id: number
      model?: ModelsOptions
      model_id: number
      name: string
      notes?: string
      purchased_at?: string | Date
      requestable: boolean
      serial?: string
      updated_at: string | Date
      vendor?: VendorsOptions
      vendor_id?: number
    }
  }
}
