// TypesFromSerializers CacheKey f2bf6a5fde7ae36ce60bf8c7bd18078f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from '../Categories/Options'
import type DepartmentsOptions from '../Departments/Options'
import type IpLeasesOptions from '../IpLeases/Options'
import type LocationsOptions from '../Locations/Options'
import type ManufacturersOptions from '../Manufacturers/Options'
import type ModelsOptions from '../Models/Options'
import type StatusLabelsOptions from '../StatusLabels/Options'
import type VendorsOptions from '../Vendors/Options'

declare global {
  namespace Schema {
    interface ItemsIndex {
      id: number
      asset_tag?: string
      assigned: boolean
      category: CategoriesOptions
      cost: number
      cost_currency: string
      created_at: string | Date
      default_location_id?: number
      department: DepartmentsOptions
      ips?: IpLeasesOptions[]
      location: LocationsOptions
      manufacturer: ManufacturersOptions
      model: ModelsOptions
      model_id: number
      name: string
      notes?: string
      purchased_at?: string | Date
      requestable: boolean
      serial?: string
      status_label: StatusLabelsOptions
      status_label_id?: number
      updated_at: string | Date
      vendor: VendorsOptions
      vendor_id?: number
    }
  }
}
