// TypesFromSerializers CacheKey 3b425e164dc19e0610e4d84f69b470db
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category.d from '../Category.d'
import type Department.d from '../Department.d'
import type Location.d from '../Location.d'
import type Manufacturer.d from '../Manufacturer.d'
import type Model.d from '../Model.d'
import type StatusLabel.d from '../StatusLabel.d'
import type Vendor.d from '../Vendor.d'

export default interface ItemsIndex.d {
  id?: number
  assetTag?: string
  assigned: boolean
  category: Category.d
  cost: number
  costCurrency: string
  createdAt: string | Date
  defaultLocationId?: number
  department: Department.d
  location: Location.d
  manufacturer: Manufacturer.d
  model: Model.d
  modelId: number
  name: string
  notes?: string
  purchasedAt?: string | Date
  requestable: boolean
  serial?: string
  statusLabel: StatusLabel.d
  updatedAt: string | Date
  vendor: Vendor.d
  vendorId?: number
}

