// TypesFromSerializers CacheKey 27cadae50e5458f9b8cffbf0c8d0079d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'
import type DepartmentsOptions from '../Departments/Options'
import type IpLeasesOptions from '../IpLeases/Options'
import type Location from '../Location'
import type Manufacturer from '../Manufacturer'
import type Model from '../Model'
import type StatusLabel from '../StatusLabel'
import type Vendor from '../Vendor'

declare global {
  namespace Schema {
    interface ItemsIndex {
      id: number
      asset_tag?: string
      assigned: boolean
      category: Category
      cost: number
      cost_currency: string
      created_at: string | Date
      default_location_id?: number
      department: DepartmentsOptions
      ips?: IpLeasesOptions[]
      location: Location
      manufacturer: Manufacturer
      model: Model
      model_id: number
      name: string
      notes?: string
      purchased_at?: string | Date
      requestable: boolean
      serial?: string
      status_label: StatusLabel
      status_label_id?: number
      updated_at: string | Date
      vendor: Vendor
      vendor_id?: number
    }
  }
}
