// TypesFromSerializers CacheKey 7bf8fbb92fae81cf5d8464708f41e53e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IpLeasesOptions from '../IpLeases/Options'

declare global {
  namespace Schema {
    interface ItemsOptions {
      id: number
      created_at: string | Date
      default_location_id?: number
      ips?: IpLeasesOptions[]
      name: string
      updated_at: string | Date
    }
  }
}
