// TypesFromSerializers CacheKey 14b0bfc83f6a3e9b7b1f3997b3bea60c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { IpLeasesOptions } from '../IpLeases/Options'

declare global {
  namespace Schema {
    interface ItemsOptions {
      id: number
      default_location_id?: number
      ips?: IpLeasesOptions[]
      name: string
    }
  }
}
