// TypesFromSerializers CacheKey db393c7c21d14b21dbad5160e182b378
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Accessory from '../Accessory'
import type Assignment from '../Assignment'
import type Category from '../Category'
import type Component from '../Component'
import type Consumable from '../Consumable'
import type Location from '../Location'
import type Department from '../Department'
import type Activity from '../Activity'
import type Item from '../Item'
import type License from '../License'
import type Manufacturer from '../Manufacturer'
import type Model from '../Model'
import type Nic from '../Nic'
import type StatusLabel from '../StatusLabel'
import type Vendor from '../Vendor'

export default interface ItemsShow {
  id?: number
  accessories: Accessory[]
  assetTag?: string
  assigned: unknown
  assignments: Assignment[]
  category: Category
  components: Component[]
  consumables: Consumable[]
  cost: unknown
  costCurrency: string
  createdAt: string | Date
  defaultLocation: Location
  defaultLocationId?: number
  department: Department
  history: Activity[]
  items: Item[]
  licenses: License[]
  location: Location
  manufacturer: Manufacturer
  model: Model
  modelId: number
  name: string
  nics: Nic[]
  notes?: string
  purchasedAt?: string | Date
  requestable: boolean
  serial?: string
  statusLabel: StatusLabel
  updatedAt: string | Date
  vendor: Vendor
  vendorId?: number
}

