// TypesFromSerializers CacheKey 19a9b0d7a9f695ab21978abff1031169
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ModelsOptions from '../Models/Options'
import type StatusLabelsBasic from '../StatusLabels/Basic'

declare global {
  namespace Schema {
    interface ItemsSpotlight {
      id: string
      asset_tag?: string
      assigned: boolean
      default_location_id?: number
      model: ModelsOptions
      model_id: number
      name: string
      status_label: StatusLabelsBasic
      status_label_id?: number
      type: string
      vendor_id?: number
    }
  }
}
