// TypesFromSerializers CacheKey 45e6bde68fd327258999cb554dd03072
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PersonGroupsBasic {
      id: number
      created_at: string | Date
      description?: string
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
