// TypesFromSerializers CacheKey 6d34e64fbc36faa8e3fb6e11ffb184ec
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PersonGroupsBasic {
      id: number
      created_at: string | Date
      description?: string
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
