// TypesFromSerializers CacheKey 2367e4f077d869489bfe3df10b9f75e4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface PersonGroupsEdit {
  id: number
  slug?: string
  description?: string
  name?: string
  permissions: unknown
}

