// TypesFromSerializers CacheKey 5144f25ca59f766ece2c133264f386d7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PersonGroupsEdit {
      id: number
      description?: string
      name?: string
      permissions: {
    [key: string]: Record<string, boolean>
  }
      slug: string
    }
  }
}
