// TypesFromSerializers CacheKey e1d3c6986ddf728a9525d2e4e0a57ab5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PersonGroupsEdit {
      id: number
      description?: string
      name: string
      permissions: {
    [key: string]: Record<string, boolean>
    }
      slug: string
    }
  }
}
