// TypesFromSerializers CacheKey fc55f79f4d9af7e7a79642798e001093
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface PersonGroupsFormData {
			id?: number
			description?: string
			name?: string
			permissions: {
    [key: string]: Record<string, boolean>
    }
		}

	}
}
