// TypesFromSerializers CacheKey 4b677c1b8576ed025240aa432710c3f3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'

declare global {
  namespace Schema {
    interface PersonGroupsIndex {
      id: number
      created_at: string | Date
      description?: string
      name: string
      people: Person[]
      permissions: {
    [key: string]: Record<string, boolean>
  }
      slug: string
      updated_at: string | Date
    }
  }
}
