// TypesFromSerializers CacheKey 38d461a8afb558bd1612f9a15d39e8cd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'

declare global {
  namespace Schema {
    interface PersonGroupsIndex {
      id: number
      description?: string
      name: string
      people: Person[]
      permissions: {
    [key: string]: Record<string, boolean>
  }
      slug: string
    }
  }
}
