// TypesFromSerializers CacheKey 696ad965e0b395917195a11772546c99
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PersonGroupsOptions {
      id: number
      name?: string
      slug: string
    }
  }
}
