 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/accessories", type: :request do
  # Accessory. As you add validations to Accessory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Accessory.create! valid_attributes
      get accessories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      accessory = Accessory.create! valid_attributes
      get accessory_url(accessory)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_accessory_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      accessory = Accessory.create! valid_attributes
      get edit_accessory_url(accessory)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Accessory" do
        expect {
          post accessories_url, params: { accessory: valid_attributes }
        }.to change(Accessory, :count).by(1)
      end

      it "redirects to the created accessory" do
        post accessories_url, params: { accessory: valid_attributes }
        expect(response).to redirect_to(accessory_url(Accessory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Accessory" do
        expect {
          post accessories_url, params: { accessory: invalid_attributes }
        }.to change(Accessory, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post accessories_url, params: { accessory: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested accessory" do
        accessory = Accessory.create! valid_attributes
        patch accessory_url(accessory), params: { accessory: new_attributes }
        accessory.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the accessory" do
        accessory = Accessory.create! valid_attributes
        patch accessory_url(accessory), params: { accessory: new_attributes }
        accessory.reload
        expect(response).to redirect_to(accessory_url(accessory))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        accessory = Accessory.create! valid_attributes
        patch accessory_url(accessory), params: { accessory: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested accessory" do
      accessory = Accessory.create! valid_attributes
      expect {
        delete accessory_url(accessory)
      }.to change(Accessory, :count).by(-1)
    end

    it "redirects to the accessories list" do
      accessory = Accessory.create! valid_attributes
      delete accessory_url(accessory)
      expect(response).to redirect_to(accessories_url)
    end
  end
end
