require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/documentations", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Documentation. As you add validations to Documentation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Documentation.create! valid_attributes
      get documentations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      documentation = Documentation.create! valid_attributes
      get documentation_url(documentation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_documentation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      documentation = Documentation.create! valid_attributes
      get edit_documentation_url(documentation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Documentation" do
        expect {
          post documentations_url, params: { documentation: valid_attributes }
        }.to change(Documentation, :count).by(1)
      end

      it "redirects to the created documentation" do
        post documentations_url, params: { documentation: valid_attributes }
        expect(response).to redirect_to(documentation_url(Documentation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Documentation" do
        expect {
          post documentations_url, params: { documentation: invalid_attributes }
        }.to change(Documentation, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post documentations_url, params: { documentation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested documentation" do
        documentation = Documentation.create! valid_attributes
        patch documentation_url(documentation), params: { documentation: new_attributes }
        documentation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the documentation" do
        documentation = Documentation.create! valid_attributes
        patch documentation_url(documentation), params: { documentation: new_attributes }
        documentation.reload
        expect(response).to redirect_to(documentation_url(documentation))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        documentation = Documentation.create! valid_attributes
        patch documentation_url(documentation), params: { documentation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested documentation" do
      documentation = Documentation.create! valid_attributes
      expect {
        delete documentation_url(documentation)
      }.to change(Documentation, :count).by(-1)
    end

    it "redirects to the documentations list" do
      documentation = Documentation.create! valid_attributes
      delete documentation_url(documentation)
      expect(response).to redirect_to(documentations_url)
    end
  end
end
