// TypesFromSerializers CacheKey f4502f896f11ff3b57d3f71e5f1d211c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Company from '../Company'

declare global {
  namespace Schema {
    interface LdapsEdit {
      id: number
      company: Company
      domain?: string
      host?: string
      name: string
      password?: string
      port?: string
      sync_interval?: string
      tree_base?: string
      user_search?: string
      username?: string
    }
  }
}
