// TypesFromSerializers CacheKey 4f303d7d26710cd9a322e2045e9ea5e5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Company from '../Company'

declare global {
  namespace Schema {
    interface LdapsIndex {
      id: number
      company: Company
      created_at: string | Date
      domain?: string
      host?: string
      name: string
      password?: string
      port?: string
      sync_interval?: string
      tree_base?: string
      updated_at: string | Date
      user_search?: string
      username?: string
    }
  }
}
