// TypesFromSerializers CacheKey b82429409a8926b4cbe61911a19780df
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Company from '../Company'

export default interface LdapsIndex {
  id?: number
  company: Company
  createdAt: string | Date
  domain?: string
  host?: string
  name: string
  password?: string
  port?: string
  syncInterval?: string
  treeBase?: string
  updatedAt: string | Date
  userSearch?: string
  username?: string
}

