// TypesFromSerializers CacheKey b10888ec2ed61fae19944037eb7b123e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface SmtpsEdit {
      id: number
      address?: string
      domain?: string
      host: string
      name: string
      notes?: string
      password?: string
      port?: number
      security: number
      username?: string
    }
  }
}
