// TypesFromSerializers CacheKey 008667ab3de0b1c29ad81c3442e5c399
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface SmtpsEdit {
      id: number
      address?: string
      domain?: string
      host: string
      name: string
      notes?: string
      password?: string
      port?: number
      security: "plain" | "tls" | "ssl"
      username?: string
    }
  }
}
