// TypesFromSerializers CacheKey 4a7344127cf26738046d14e43320f243
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface SmtpsFormData {
      id?: number
      address?: string
      auth?: string
      domain?: string
      name?: string
      notes?: string
      password?: string
      port?: number
      security: number
      username?: string
    }
  }
}
