// TypesFromSerializers CacheKey 53375fec695dc49580d4c914ede89585
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface SmtpsFormData {
      id?: number
      address?: string
      domain?: string
      host: string
      name: string
      notes?: string
      password?: string
      port?: number
      security: "plain" | "tls" | "ssl"
      username?: string
    }
  }
}
