// TypesFromSerializers CacheKey 9f671ca96723abddb5bd73dd8730eaa9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from '../Categories/Options'
import type Department from '../Department'
import type Vendor from '../Vendor'

declare global {
  namespace Schema {
    interface ContractsBasic {
      id: number
      begins_at?: string | Date
      category?: CategoriesOptions
      category_id: number
      created_at: string | Date
      department?: Department
      ends_at?: string | Date
      name: string
      notes?: string
      number?: string
      slug: string
      updated_at: string | Date
      vendor: Vendor
      vendor_id: number
    }
  }
}
