// TypesFromSerializers CacheKey c6e1ce67fa0bcc87880b90ca6e71cbac
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface ContractsEdit {
			id?: number
			beginsAt?: string | Date
			categoryId: number
			endsAt?: string | Date
			name: string
			notes?: string
			number?: string
			vendorId: number
		}

	}
}
