// TypesFromSerializers CacheKey cf04d1d4470f7714b2f155a9af400ef8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface ContractsEdit {
			id: number
			begins_at?: string | Date
			category_id: number
			ends_at?: string | Date
			name: string
			notes?: string
			number?: string
			vendor_id: number
		}

	}
}
