// TypesFromSerializers CacheKey 4dbcc2370ee2d4b84ded1c0317a6a84a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ContractsFormData {
      id?: number
      begins_at?: string | Date
      category_id: number
      ends_at?: string | Date
      name: string
      notes?: string
      number?: string
      vendor_id: number
    }
  }
}
