// TypesFromSerializers CacheKey 182c5fa8dd3e8f0cbc76258ab6233868
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'
import type Department from '../Department'
import type Vendor from '../Vendor'

declare global {
  namespace Schema {
    interface ContractsIndex {
      id: number
      begins_at?: string | Date
      category: Category
      category_id: number
      created_at: string | Date
      department: Department
      ends_at?: string | Date
      name: string
      notes?: string
      number?: string
      slug: string
      updated_at: string | Date
      vendor: Vendor
      vendor_id: number
    }
  }
}
