// TypesFromSerializers CacheKey e328b6a72a54c653df1837115c1e02f3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Category } from '../Category'
import type { Department } from '../Department'
import type { Vendor } from '../Vendor'

declare global {
	 declare namespace Schema {
		export interface ContractsIndex {
			id?: number
			beginsAt?: string | Date
			category: Category
			categoryId: number
			createdAt: string | Date
			department: Department
			endsAt?: string | Date
			name: string
			notes?: string
			number?: string
			updatedAt: string | Date
			vendor: Vendor
			vendorId: number
		}

	}
}
