// TypesFromSerializers CacheKey 10c6e9ed2d88c3217c52295285257fac
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Activity from '../Activity'
import type Category from '../Category'
import type Department from '../Department'
import type Vendor from '../Vendor'

export default interface ContractsShow {
  id?: number
  activities: Activity
  beginsAt?: string | Date
  category: Category
  categoryId: number
  createdAt: string | Date
  department: Department
  endsAt?: string | Date
  name: string
  notes?: string
  number?: string
  updatedAt: string | Date
  vendor: Vendor
  vendorId: number
}

