// TypesFromSerializers CacheKey 9455c6781fee94bd7202eb11b09946db
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from '../Categories/Options'
import type VendorsOptions from '../Vendors/Options'

declare global {
  namespace Schema {
    interface ContractsSpotlight {
      id: string
      category: CategoriesOptions
      category_id: number
      name: string
      number?: string
      slug: string
      vendor: VendorsOptions
      vendor_id: number
    }
  }
}
