// TypesFromSerializers CacheKey 293f5666e4a80a4e6062cfa6b19f4d1f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ActivityPersonActivity {
      id: number
      active: boolean
      department_id: unknown
      employee_number?: string
      first_name: string
      job_title?: string
      last_name: string
      location_id?: number
      manager_id?: number
      middle_name?: string
      name: string
      user_id?: number
    }
  }
}
