// TypesFromSerializers CacheKey d034898d0b5544ed8281c80ec8208a1c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ActivityUserActivity {
      id: number
      active: boolean
      email: string
    }
  }
}
