// TypesFromSerializers CacheKey 67c7af12f514436b6a99792b30d7b1b9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleFormDataPersonUserFormData {
      id?: number
      active: boolean
      email: string
    }
  }
}
