// TypesFromSerializers CacheKey 60cf98f276001339729c3756bdcf0a57
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CompaniesOptions from '../../Companies/Options'

declare global {
  namespace Schema {
    interface UsersShowShowUserPerson {
      id?: number
      active: boolean
      company: CompaniesOptions
      department_id: unknown
      employee_number?: string
      first_name: string
      job_title?: string
      last_name: string
      location_id?: number
      manager_id?: number
      middle_name?: string
      name: string
      user_id?: number
    }
  }
}
