// TypesFromSerializers CacheKey d4abd634bce0804ac32e606adad155f0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'
import type Manufacturer from '../Manufacturer'
import type Model from '../Model'
import type StatusLabel from '../StatusLabel'
import type Vendor from '../Vendor'

declare global {
  namespace Schema {
    interface AssetsBasic {
      id: number
      asset_tag?: string
      available_to_checkout: unknown
      category: Category
      cost: number
      cost_currency: string
      created_at: string | Date
      default_location_id?: number
      manufacturer: Manufacturer
      min_qty?: number
      model: Model
      model_id: number
      name: string
      notes?: string
      purchased_at?: string | Date
      qty?: number
      requestable: boolean
      serial?: string
      status_label: StatusLabel
      status_label_id?: number
      type: string
      updated_at: string | Date
      vendor: Vendor
      vendor_id?: number
    }
  }
}
