// TypesFromSerializers CacheKey 1d6c87fd35ef974a9d0209c36b19336e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Assignment } from '../Assignment'
import type { Category } from '../Category'
import type { Department } from '../Department'
import type { Location } from '../Location'
import type { Manufacturer } from '../Manufacturer'
import type { Model } from '../Model'
import type { StatusLabel } from '../StatusLabel'
import type { Vendor } from '../Vendor'

declare export global {
	declare namespace Schema {
		export interface AssetsIndex {
			id?: number
			asset_tag?: string
			assignments: Assignment[]
			available_to_checkout: unknown
			category: Category
			cost: unknown
			cost_currency: string
			created_at: string | Date
			default_location_id?: number
			department: Department
			location: Location
			manufacturer: Manufacturer
			min_qty?: number
			model: Model
			model_id: number
			name: string
			notes?: string
			purchased_at?: string | Date
			qty?: number
			requestable: boolean
			serial?: string
			status_label: StatusLabel
			type: string
			updated_at: string | Date
			vendor: Vendor
			vendor_id?: number
		}

	}
}
