// TypesFromSerializers CacheKey 92c841e4246b6a25667c52f43e2b10c8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface AssetsOptions {
      id: number
      name: string
    }
  }
}
