// TypesFromSerializers CacheKey 748406d933fb5bd555ef25710227b3e6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface AssetsOptions {
      id: number
      name: string
    }
  }
}
