// TypesFromSerializers CacheKey 96196b49c064bd639081b1d87b2f2442
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface UsersEdit {
  id?: number
  active: boolean
  activeCompanyId?: number
  email: string
}

