// TypesFromSerializers CacheKey 6845d2a19330e75c693d3c6d85aef824
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface UsersEdit {
			id?: number
			active: boolean
			active_company_id?: number
			email: string
		}

	}
}
