// TypesFromSerializers CacheKey 792b729e4a327e12504a0ae488084d50
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type UserTablePreferences from '../../UserTablePreferences'
import type UserPreferences from '../../UserPreferences'
import type CompaniesOptions from '../Companies/Options'
import type Person from '../Person'
import type Role from '../Role'

declare global {
  namespace Schema {
    interface UsersFlash {
      id: number
      active: boolean
      active_company: CompaniesOptions
      active_company_id?: number
      companies: CompaniesOptions[]
      email: string
      people: Person[]
      person: Person
      roles: Role[]
      table_preferences: UserTablePreferences
      user_preferences: UserPreferences
    }
  }
}
