// TypesFromSerializers CacheKey 29826171f21e7d6f1b6db6f9501bf913
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface UsersFormData {
      id?: number
      active: boolean
      active_company_id?: number
      email: string
      password: unknown
      password_confirmation: unknown
    }
  }
}
