// TypesFromSerializers CacheKey 3e13ba0421b5674210b7f4a135f10e09
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface UsersFormData {
			id?: number
			active: boolean
			active_company_id?: number
			email: string
		}

	}
}
