// TypesFromSerializers CacheKey fc2a49e1b6bbda93c7cdd747c38478d0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type UserTablePreferences from '../../UserTablePreferences'
import type UserPreferences from '../../UserPreferences'
import type Company from '../Company'
import type Activity from '../Activity'
import type Person from '../Person'
import type Role from '../Role'

declare global {
  namespace Schema {
    interface UsersIndex {
      id: number
      active: boolean
      active_company: Company
      active_company_id?: number
      activities: Activity[]
      companies: Company[]
      created_at: string | Date
      email: string
      people: Person[]
      person: Person
      roles: Role[]
      table_preferences: UserTablePreferences
      updated_at: string | Date
      user_preferences: UserPreferences
    }
  }
}
