// TypesFromSerializers CacheKey fb9634db79915bda125977693a53be11
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Company } from '../Company'
import type { Activity } from '../Activity'
import type { Person } from '../Person'
import type { Role } from '../Role'

declare global {
  namespace Schema {
    interface UsersIndex {
      id: number
      active: boolean
      active_company: Company
      active_company_id?: number
      activities: Activity[]
      companies: Company[]
      confirmation_sent_at?: string | Date
      confirmed_at?: string | Date
      created_at: string | Date
      current_sign_in_at?: string | Date
      current_sign_in_ip?: string
      email: string
      failed_attempts: number
      last_sign_in_at?: string | Date
      last_sign_in_ip?: string
      locked_at?: string | Date
      people: Person[]
      person: Person
      remember_created_at?: string | Date
      reset_password_sent_at?: string | Date
      roles: Role[]
      sign_in_count: number
      table_preferences: Record<string, string>
      unconfirmed_email?: string
      updated_at: string | Date
      user_preferences: Record<string, string>
    }
  }
}
