// TypesFromSerializers CacheKey 984384ed614548cbe388a192405ec1bd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface UsersNew {
  id?: number
  active: boolean
  activeCompanyId?: number
  email: string
}

