// TypesFromSerializers CacheKey 2ee2fc5ae8d5011716751938cc367bde
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Company } from '../Company'
import type { Activity } from '../Activity'
import type { Person } from '../Person'
import type { Role } from '../Role'

declare global {
	 declare namespace Schema {
		export interface UsersShow {
			id?: number
			active: boolean
			activeCompany: Company
			activeCompanyId?: number
			activities: Activity[]
			companies: Company[]
			confirmationSentAt?: string | Date
			confirmedAt?: string | Date
			createdAt: string | Date
			currentSignInAt?: string | Date
			currentSignInIp?: string
			email: string
			failedAttempts: number
			lastSignInAt?: string | Date
			lastSignInIp?: string
			lockedAt?: string | Date
			people: Person[]
			rememberCreatedAt?: string | Date
			resetPasswordSentAt?: string | Date
			roles: Role[]
			signInCount: number
			tablePreferences: unknown
			unconfirmedEmail?: string
			updatedAt: string | Date
			userPreferences: unknown
		}

	}
}
