// TypesFromSerializers CacheKey d9613d9e065a67f2b9683200cd04bae4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DepartmentsCounts {
      id?: number
      slug?: string
      counts: {
    items: number
    accessories: number
    consumables: number
    components: number
    licenses: number
    contracts: number
    people: number
  }
      location_id?: number
      manager_id?: number
      name: string
      notes?: string
    }
  }
}
