// TypesFromSerializers CacheKey a7c18c0ef0cc80111f0de688f48307db
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface DepartmentsEdit {
      id: number
      location_id?: number
      name?: string
      notes?: string
      slug: string
    }
  }
}
