// TypesFromSerializers CacheKey 89a144c7acd00717847848f9ba404292
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type LocationsOptions from '../Locations/Options'

declare global {
  namespace Schema {
    interface DepartmentsEdit {
      id: number
      location?: LocationsOptions
      location_id?: number
      name?: string
      notes?: string
      slug: string
    }
  }
}
