// TypesFromSerializers CacheKey bb5729d14b32aad73ec1a8c746f4fdbb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface DepartmentsEdit {
			id?: number
			locationId?: number
			name?: string
			notes?: string
			slug: string
		}

	}
}
