// TypesFromSerializers CacheKey c8a1cf48d3041b9c9a50cd057c222388
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type LocationsOptions from '../Locations/Options'

declare global {
  namespace Schema {
    interface DepartmentsFormData {
      id?: number
      location?: LocationsOptions
      location_id?: number
      name?: string
      notes?: string
    }
  }
}
