// TypesFromSerializers CacheKey d9e2786902e79c1ae133de8a84339d7c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type LocationsOptions from '../Locations/Options'
import type PeopleOptions from '../People/Options'

declare global {
  namespace Schema {
    interface DepartmentsFormData {
      id?: number
      slug?: string
      location?: LocationsOptions
      location_id?: number
      manager?: PeopleOptions
      manager_id?: number
      name: string
      notes?: string
    }
  }
}
