// TypesFromSerializers CacheKey 851ee75b565b3a63943fce6e7df86cde
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type LocationsOptions from '../Locations/Options'

declare global {
  namespace Schema {
    interface DepartmentsFormData {
      id?: number
      location?: LocationsOptions
      location_id?: number
      name: string
      notes?: string
    }
  }
}
