// TypesFromSerializers CacheKey 3e7b1d43526944284de1d728888f8775
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Accessory } from '../Accessory'
import type { Component } from '../Component'
import type { Consumable } from '../Consumable'
import type { Item } from '../Item'
import type { License } from '../License'
import type { Person } from '../Person'

declare export global {
	declare namespace Schema {
		export interface DepartmentsIndex {
			id?: number
			accessories: Accessory[]
			components: Component[]
			consumables: Consumable[]
			counts: unknown
			created_at: string | Date
			items: Item[]
			licenses: License[]
			location_id?: number
			name?: string
			notes?: string
			people: Person[]
			slug: string
			updated_at: string | Date
		}

	}
}
