// TypesFromSerializers CacheKey 4744a6a688826e0a9af98d77f9ab858e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Accessory } from '../Accessory'
import type { Component } from '../Component'
import type { Consumable } from '../Consumable'
import type { Item } from '../Item'
import type { License } from '../License'
import type { Person } from '../Person'

declare export global {
	declare namespace Schema {
		export interface DepartmentsIndex {
			id: number
			accessories: Accessory[]
			components: Component[]
			consumables: Consumable[]
			counts: {
    items: number
    accessories: number
    consumables: number
    components: number
    licenses: number
    contracts: number
    people: number
  }
			created_at: string | Date
			items: Item[]
			licenses: License[]
			location_id?: number
			name?: string
			notes?: string
			people: Person[]
			slug: string
			updated_at: string | Date
		}

	}
}
