// TypesFromSerializers CacheKey d3a22199d4d941f2bd89775f7878235c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface DepartmentsNew {
  id?: number
  locationId?: number
  name?: string
  notes?: string
}

