// TypesFromSerializers CacheKey 7f6f491c5fd9b0833b189d2438e0a03d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface DepartmentsNew {
			id?: number
			location_id?: number
			name?: string
			notes?: string
		}

	}
}
