// TypesFromSerializers CacheKey 09eb6ab6c20334c65065cb0af082dd76
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface DepartmentsOptions {
			id: number
			name?: string
		}

	}
}
