// TypesFromSerializers CacheKey 090a20d05c7edb7285ec4c31b8bf3208
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Accessory } from '../Accessory'
import type { Activity } from '../Activity'
import type { Component } from '../Component'
import type { Consumable } from '../Consumable'
import type { Item } from '../Item'
import type { License } from '../License'
import type { Location } from '../Location'
import type { Person } from '../Person'

declare export global {
	declare namespace Schema {
		export interface DepartmentsShow {
			id?: number
			accessories: Accessory[]
			activities: Activity[]
			components: Component[]
			consumables: Consumable[]
			counts: unknown
			created_at: string | Date
			items: Item[]
			licenses: License[]
			location: Location
			location_id?: number
			name?: string
			notes?: string
			people: Person[]
			slug: string
			updated_at: string | Date
		}

	}
}
