// TypesFromSerializers CacheKey 7da52505427329d6bbfaca0a489880a4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Accessory from '../Accessory'
import type Activity from '../Activity'
import type Component from '../Component'
import type Consumable from '../Consumable'
import type Item from '../Item'
import type License from '../License'
import type Location from '../Location'
import type Person from '../Person'

export default interface DepartmentsShow {
  id?: number
  accessories: Accessory[]
  activities: Activity[]
  components: Component[]
  consumables: Consumable[]
  counts: unknown
  createdAt: string | Date
  items: Item[]
  licenses: License[]
  location: Location[]
  locationId?: number
  name?: string
  notes?: string
  people: Person[]
  slug: string
  updatedAt: string | Date
}

