// TypesFromSerializers CacheKey d3b0ea17977968ccf51d80053be1f23e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Accessory } from '../Accessory'
import type { Activity } from '../Activity'
import type { Component } from '../Component'
import type { Consumable } from '../Consumable'
import type { Item } from '../Item'
import type { License } from '../License'
import type { Location } from '../Location'
import type { Person } from '../Person'

declare global {
	 declare namespace Schema {
		export interface DepartmentsShow {
			id?: number
			accessories: Accessory[]
			activities: Activity[]
			components: Component[]
			consumables: Consumable[]
			counts: unknown
			createdAt: string | Date
			items: Item[]
			licenses: License[]
			location: Location
			locationId?: number
			name?: string
			notes?: string
			people: Person[]
			slug: string
			updatedAt: string | Date
		}

	}
}
