// TypesFromSerializers CacheKey b97cb57412282e846c63efddb1f7f75c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface ConsumablesCheckin {
			id?: number
			cost: unknown
			costCurrency: string
			createdAt: string | Date
			defaultLocationId?: number
			minQty?: number
			modelId: number
			name: string
			notes?: string
			qty?: number
			qtyAvailable: unknown
			requestable: boolean
			updatedAt: string | Date
			vendorId?: number
		}

	}
}
