// TypesFromSerializers CacheKey e30ee08eb996dfde154e8e001b84ccd0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface ConsumablesCheckin {
			id?: number
			cost: unknown
			cost_currency: string
			created_at: string | Date
			default_location_id?: number
			min_qty?: number
			model_id: number
			name: string
			notes?: string
			qty?: number
			qty_available: unknown
			requestable: boolean
			updated_at: string | Date
			vendor_id?: number
		}

	}
}
