// TypesFromSerializers CacheKey 46d22caa13b6246015413529373928ca
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface ConsumablesCheckin {
			id?: number
			cost: number
			cost_currency: string
			created_at: string | Date
			default_location_id?: number
			min_qty?: number
			model_id: number
			name: string
			notes?: string
			qty?: number
			qty_available: number
			requestable: boolean
			updated_at: string | Date
			vendor_id?: number
		}

	}
}
