// TypesFromSerializers CacheKey 8d45035de624899a5f0a0a0b52063dc2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface ConsumablesEdit {
			id: number
			cost: number
			cost_currency: string
			default_location_id?: number
			min_qty?: number
			model_id: number
			name: string
			notes?: string
			qty?: number
			qty_available: number
			requestable: boolean
			vendor_id?: number
		}

	}
}
