// TypesFromSerializers CacheKey 1c06220415f344a770460c57a5e8c293
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface ConsumablesEdit {
			id?: number
			cost: unknown
			cost_currency: string
			default_location_id?: number
			min_qty?: number
			model_id: number
			name: string
			notes?: string
			qty?: number
			qty_available: unknown
			requestable: boolean
			vendor_id?: number
		}

	}
}
