// TypesFromSerializers CacheKey de128302fd1e554ee819072c34e998b5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface ConsumablesEdit {
			id?: number
			cost: number
			cost_currency: string
			default_location_id?: number
			min_qty?: number
			model_id: number
			name: string
			notes?: string
			qty?: number
			qty_available: number
			requestable: boolean
			vendor_id?: number
		}

	}
}
