// TypesFromSerializers CacheKey 9ad32f9409933b6f51c56861bc76e6e0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ConsumablesFormData {
      id?: number
      cost: number
      cost_currency: string
      default_location_id?: number
      min_qty?: number
      model_id: number
      name: string
      notes?: string
      qty?: number
      qty_available: number
      requestable: boolean
      vendor_id?: number
    }
  }
}
