// TypesFromSerializers CacheKey f8e916437fb1e62e77441697ef3a26d7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../Money'
import type LocationsOptions from '../Locations/Options'
import type ModelsOptions from '../Models/Options'
import type VendorsOptions from '../Vendors/Options'

declare global {
  namespace Schema {
    interface ConsumablesFormData {
      id: number
      cost: Money
      cost_currency: string
      default_location?: LocationsOptions
      default_location_id?: number
      min_qty?: number
      model?: ModelsOptions
      model_id: number
      name: string
      notes?: string
      qty?: number
      qty_available: number
      requestable: boolean
      vendor?: VendorsOptions
      vendor_id?: number
    }
  }
}
