// TypesFromSerializers CacheKey 5808a9b1ea9ce10fccb1bc3ee395c39f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Category } from '../Category'
import type { Manufacturer } from '../Manufacturer'
import type { Model } from '../Model'
import type { Vendor } from '../Vendor'

declare export global {
	declare namespace Schema {
		export interface ConsumablesIndex {
			id?: number
			category: Category
			cost: unknown
			cost_currency: string
			created_at: string | Date
			default_location_id?: number
			manufacturer: Manufacturer
			min_qty?: number
			model: Model
			model_id: number
			name: string
			notes?: string
			qty?: number
			qty_available: unknown
			requestable: boolean
			updated_at: string | Date
			vendor: Vendor
			vendor_id?: number
		}

	}
}
