// TypesFromSerializers CacheKey 0867aa008adf3bcca9c09086bea02b98
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface ConsumablesNew {
			id?: number
			cost: unknown
			cost_currency: string
			default_location_id?: number
			min_qty?: number
			model_id: number
			name: string
			notes?: string
			qty?: number
			qty_available: unknown
			requestable: boolean
			vendor_id?: number
		}

	}
}
