// TypesFromSerializers CacheKey 5f3315a96d0b18b7962dddb64982ba6a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ConsumablesOptions {
      id: number
      name: string
      qty_available: number
    }
  }
}
