// TypesFromSerializers CacheKey cd240e3d0b8315233e68736e534810d5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ConsumablesOptions {
      id: number
      created_at: string | Date
      name: string
      qty_available: number
      updated_at: string | Date
    }
  }
}
