// TypesFromSerializers CacheKey 830bfcb48d25b67951f268cd376e22ab
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Assignment } from '../Assignment'
import type { Category } from '../Category'
import type { Location } from '../Location'
import type { Manufacturer } from '../Manufacturer'
import type { Model } from '../Model'
import type { Purchase } from '../Purchase'
import type { Vendor } from '../Vendor'

declare export global {
	declare namespace Schema {
		export interface ConsumablesShow {
			id?: number
			assignments: Assignment[]
			category: Category
			cost: unknown
			cost_currency: string
			created_at: string | Date
			default_location: Location
			default_location_id?: number
			manufacturer: Manufacturer
			min_qty?: number
			model: Model
			model_id: number
			name: string
			notes?: string
			purchase: Purchase
			qty?: number
			qty_available: unknown
			requestable: boolean
			updated_at: string | Date
			vendor: Vendor
			vendor_id?: number
		}

	}
}
