// TypesFromSerializers CacheKey 9f7cdebe2000b86c40718dd66e61764b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Activity } from '../Activity'
import type { Assignment } from '../Assignment'
import type { Category } from '../Category'
import type { Location } from '../Location'
import type { Manufacturer } from '../Manufacturer'
import type { Model } from '../Model'
import type { Purchase } from '../Purchase'
import type { Vendor } from '../Vendor'

declare global {
  namespace Schema {
    interface ConsumablesShow {
      id: number
      activities: Activity[]
      assignments: Assignment[]
      category: Category
      cost: number
      cost_currency: string
      created_at: string | Date
      default_location: Location
      default_location_id?: number
      manufacturer: Manufacturer
      min_qty?: number
      model: Model
      model_id: number
      name: string
      notes?: string
      purchase: Purchase
      qty?: number
      qty_available: number
      requestable: boolean
      updated_at: string | Date
      vendor: Vendor
      vendor_id?: number
    }
  }
}
