// TypesFromSerializers CacheKey c19f7b4d73ce7472e6b3b4bc4f00b915
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface StatusLabelsBasic {
      id: number
      created_at: string | Date
      description?: string
      name: string
      slug: string
      status_type: "deployable" | "pending" | "undeployable" | "archived"
      updated_at: string | Date
    }
  }
}
