// TypesFromSerializers CacheKey 6f7b5a1b3619a5decfa30bda744265c0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface StatusLabelsEdit {
      id: number
      description?: string
      name?: string
      slug: string
      status_type: number
    }
  }
}
