// TypesFromSerializers CacheKey 58a065edf41e5017cf7bed811bf1db71
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface StatusLabelsEdit {
  id: number
  slug?: string
  description?: string
  name?: string
  statusType: number
}

