// TypesFromSerializers CacheKey 27dc44dcf8136d07ec5d48b078e77065
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface StatusLabelsIndex {
      id: number
      created_at: string | Date
      description?: string
      name: string
      slug: string
      status_type: "deployable" | "pending" | "undeployable" | "archived"
      updated_at: string | Date
    }
  }
}
