// TypesFromSerializers CacheKey e3e530f29787d24897a1e99aeade1aa4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface StatusLabelsIndex {
      id: number
      created_at: string | Date
      description?: string
      name: string
      slug: string
      status_type: number
      updated_at: string | Date
    }
  }
}
