// TypesFromSerializers CacheKey 62830129ad5d5142ce5284bbc9af836e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface StatusLabelsOptions {
			id: number
			name?: string
			status_type: number
		}

	}
}
