// TypesFromSerializers CacheKey 0c40686ac7be1d2f43e96eedf50b5667
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface StatusLabelsOptions {
      id: number
      name: string
      slug: string
      status_type: number
    }
  }
}
