// TypesFromSerializers CacheKey 13da7f1ad4b09742192bb9770effbc54
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface StatusLabelsOptions {
      id: number
      name: string
      status_type: number
    }
  }
}
