// TypesFromSerializers CacheKey a60add0afea6e3ae523fe5a7d6671f65
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface StatusLabelsShow {
			id: number
			created_at: string | Date
			description?: string
			name?: string
			slug: string
			status_type: number
			updated_at: string | Date
		}

	}
}
