// TypesFromSerializers CacheKey 4489ecdd357db5f8f5207c02ac89794b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface StatusLabelsShow {
      id: number
      created_at: string | Date
      description?: string
      name: string
      slug: string
      status_type: "deployable" | "pending" | "undeployable" | "archived"
      updated_at: string | Date
    }
  }
}
