// TypesFromSerializers CacheKey ed689d2be0235938a0be55e11a6ebee8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../Money'
import type OrdersBasic from '../Orders/Basic'
import type Purchasable from '../Purchasable'

declare global {
  namespace Schema {
    interface PurchasesBasic {
      id: number
      cost: Money
      cost_currency: string
      created_at: string | Date
      notes?: string
      order: OrdersBasic
      order_id?: number
      purchasable: Purchasable
      purchasable_id: number
      purchasable_type: string
      qty?: number
      updated_at: string | Date
    }
  }
}
