// TypesFromSerializers CacheKey a10c350595021dc51b5b36874c11b5c3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IpLeasesOptions {
      id?: number
      address?: string
    }
  }
}
