// TypesFromSerializers CacheKey 030d422d51234dd1b0078b13e291b580
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface IpLeasesOptions {
      id: number
      active: boolean
      address?: string
    }
  }
}
