// TypesFromSerializers CacheKey 2151bc77841dbb6e1735277eaa7894de
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface IpLeasesOptions {
  id?: number
  address?: unknown
}

