// TypesFromSerializers CacheKey e547e222b27a95eb892e3e8b5cdc84bc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'
import type Manufacturer from '../Manufacturer'

declare global {
  namespace Schema {
    interface ModelsBasic {
      id: number
      category: Category
      category_id: number
      created_at: string | Date
      manufacturer: Manufacturer
      manufacturer_id: number
      model_number?: string
      name: string
      notes?: string
      slug: string
      updated_at: string | Date
    }
  }
}
