// TypesFromSerializers CacheKey c66568463d5c2949fd7e9b496309b582
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'
import type Manufacturer from '../Manufacturer'

declare global {
  namespace Schema {
    interface ModelsBasic {
      id: number
      category: Category
      category_id: number
      created_at: string | Date
      manufacturer: Manufacturer
      manufacturer_id: number
      model_number?: string
      name: string
      notes?: string
      slug: string
      updated_at: string | Date
    }
  }
}
