// TypesFromSerializers CacheKey 3d30e41ee3450b48567545c9e601f5ee
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ModelsEdit {
      id: number
      category_id: number
      manufacturer_id: number
      model_number?: string
      name?: string
      notes?: string
      slug: string
    }
  }
}
