// TypesFromSerializers CacheKey a87d1bde82a9d3c13f63fad9108d8dd0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface ModelsEdit {
  id?: number
  categoryId: number
  manufacturerId: number
  modelNumber?: string
  name?: string
  notes?: string
  slug: string
}

