// TypesFromSerializers CacheKey cacdd40df363585e29c66d1dbaf8c023
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface ModelsEdit {
			id?: number
			category_id: number
			manufacturer_id: number
			model_number?: string
			name?: string
			notes?: string
			slug: string
		}

	}
}
