// TypesFromSerializers CacheKey 571df38ed1a79ba1074a4accbd5a7616
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ModelsFormData {
      id?: number
      slug?: string
      category_id?: number
      manufacturer_id?: number
      model_number?: string
      name?: string
      notes?: string
    }
  }
}
