// TypesFromSerializers CacheKey abe94babc81dd8b52607846ba1bbcbbb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from '../Categories/Options'
import type ManufacturersOptions from '../Manufacturers/Options'

declare global {
  namespace Schema {
    interface ModelsFormData {
      id?: number
      slug?: string
      category?: CategoriesOptions
      category_id: number
      manufacturer?: ManufacturersOptions
      manufacturer_id: number
      model_number?: string
      name: string
      notes?: string
    }
  }
}
