// TypesFromSerializers CacheKey d6fdec4fce2aff6e63ccbae0850ef49c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface ModelsFormData {
			id?: number
			category_id: number
			manufacturer_id: number
			model_number?: string
			name?: string
			notes?: string
			slug: string
		}

	}
}
