// TypesFromSerializers CacheKey 683cc6cc80653c976956f327a7a5ffcc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Category } from '../Category'
import type { Manufacturer } from '../Manufacturer'

declare export global {
	declare namespace Schema {
		export interface ModelsIndex {
			id?: number
			category: Category
			category_id: number
			count: unknown
			created_at: string | Date
			manufacturer: Manufacturer
			manufacturer_id: number
			model_number?: string
			name?: string
			notes?: string
			slug: string
			updated_at: string | Date
		}

	}
}
