// TypesFromSerializers CacheKey a2de6f80ed6e871565b259bd52fc422d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from '../Categories/Options'
import type ManufacturersBasic from '../Manufacturers/Basic'

declare global {
  namespace Schema {
    interface ModelsIndex {
      id: number
      category: CategoriesOptions
      category_id: number
      count: number
      created_at: string | Date
      manufacturer: ManufacturersBasic
      manufacturer_id: number
      model_number?: string
      name: string
      notes?: string
      slug: string
      updated_at: string | Date
    }
  }
}
