// TypesFromSerializers CacheKey dc5021b2b23801c4a970b92df7094917
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface ModelsNew {
			id?: number
			category_id: number
			manufacturer_id: number
			model_number?: string
			name?: string
			notes?: string
			slug: string
		}

	}
}
