// TypesFromSerializers CacheKey b13350dedb1ea5585ce39fd2d4ddbc72
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface ModelsOptions {
			id?: number
			name?: string
		}

	}
}
