// TypesFromSerializers CacheKey a777d9e17723cf6b6260b5b29ae69003
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ModelsOptions {
      id: number
      name: string
      slug: string
    }
  }
}
