// TypesFromSerializers CacheKey 100d36a0c597ab10afedce010dbbad1a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ModelsOptions {
      id: number
      slug?: string
      name: string
    }
  }
}
