// TypesFromSerializers CacheKey be90ef60a95057f0c519e39d286fba82
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface AddressesFormData {
			id?: number
			address: string
			address_2?: string
			category_id: number
			city?: string
			contact_id: number
			country?: string
			notes?: string
			postal?: string
			region?: string
		}

	}
}
