// TypesFromSerializers CacheKey c47e6526f72cc4d28258c2ec77120782
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from '../Categories/Options'

declare global {
  namespace Schema {
    interface AddressesFormData {
      id?: number
      address: string
      address_2?: string
      category: CategoriesOptions
      category_id: number
      city?: string
      contact_id: number
      country?: string
      notes?: string
      postal?: string
      region?: string
    }
  }
}
