// TypesFromSerializers CacheKey eeeb376dd2e9265ea46b70e51a17f92c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../Money'
import type VendorsOptions from '../Vendors/Options'

declare global {
  namespace Schema {
    interface OrdersBasic {
      id: number
      canceled_at?: string | Date
      canceled_reason?: string
      cost: Money
      created_at: string | Date
      delivered_at?: string | Date
      discount_cost: Money
      discount_decription?: string
      expected_at?: string | Date
      notes?: string
      number?: string
      ordered_at?: string | Date
      returned_at?: string | Date
      returned_reason?: string
      shipping_cost: Money
      submitted_at?: string | Date
      tax_cost: Money
      updated_at: string | Date
      user_id: number
      vendor: VendorsOptions
      vendor_id: number
    }
  }
}
