// TypesFromSerializers CacheKey 3a949fa615976299bf5e979496022b98
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type VendorsOptions from '../Vendors/Options'

declare global {
  namespace Schema {
    interface OrdersBasic {
      id: number
      canceled_at?: string | Date
      canceled_reason?: string
      cost: number
      created_at: string | Date
      delivered_at?: string | Date
      discount_cost: number
      discount_decription?: string
      expected_at?: string | Date
      notes?: string
      number?: string
      ordered_at?: string | Date
      returned_at?: string | Date
      returned_reason?: string
      shipping_cost: number
      submitted_at?: string | Date
      tax_cost: number
      updated_at: string | Date
      user_id: number
      vendor: VendorsOptions
      vendor_id: number
    }
  }
}
