// TypesFromSerializers CacheKey 92cbc094d603faf9e0751aa1afbb9239
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../Money'
import type VendorsOptions from '../Vendors/Options'

declare global {
  namespace Schema {
    interface OrdersEdit {
      id: number
      canceled_at?: string | Date
      canceled_reason?: string
      cost: Money
      delivered_at?: string | Date
      discount_cost: Money
      discount_decription?: string
      expected_at?: string | Date
      notes?: string
      number?: string
      ordered_at?: string | Date
      returned_at?: string | Date
      returned_reason?: string
      shipping_cost: Money
      submitted_at?: string | Date
      tax_cost: Money
      user_id: number
      vendor?: VendorsOptions
      vendor_id: number
    }
  }
}
