// TypesFromSerializers CacheKey 4150d16ca47ba8f0b95fadd09e55a969
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface OrdersIndex {
			id?: number
			canceled_at?: string | Date
			canceled_reason?: string
			created_at: string | Date
			delivered_at?: string | Date
			discount_cents?: number
			discount_currency: string
			discount_decription?: string
			expected_at?: string | Date
			notes?: string
			number?: string
			ordered_at?: string | Date
			returned_at?: string | Date
			returned_reason?: string
			shipping_cents?: number
			shipping_currency: string
			submitted_at?: string | Date
			tax_cents?: number
			tax_currency: string
			updated_at: string | Date
			user_id: number
			vendor_id: number
		}

	}
}
