// TypesFromSerializers CacheKey f8a97357b83afb9ee92ccf28e6c211e3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CategoriesEdit {
      id?: number
      categorizable_type: string
      description?: string
      name: string
      slug: string
    }
  }
}
