// TypesFromSerializers CacheKey eae3f45ab96d36c85cb6aaabedc3a178
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface CategoriesEdit {
			id?: number
			categorizable_type: string
			description?: string
			name?: string
			slug: string
		}

	}
}
