// TypesFromSerializers CacheKey 921af2b59f9322b6b94403e6d7d08a53
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface CategoriesEdit {
  id?: number
  categorizableType: string
  description?: string
  name?: string
  slug: string
}

