// TypesFromSerializers CacheKey 9855b36db7f27b88e98a8f430ebde613
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CategoriesEdit {
      id: number
      categorizable_type: string
      description?: string
      name: string
      plural: string
      slug: string
    }
  }
}
