// TypesFromSerializers CacheKey c85be02bf0f302a5a8c13cc562c1581c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CategoriesIndex {
      id: number
      categorizable_type: string
      created_at: string | Date
      description?: string
      name: string
      plural: string
      qty: number
      slug: string
      updated_at: string | Date
    }
  }
}
