// TypesFromSerializers CacheKey f3bebf96895c75efc29f5e896a8a73d6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CategoriesIndex {
      id?: number
      categorizable_type: string
      created_at: string | Date
      description?: string
      name: string
      qty: number
      slug: string
      updated_at: string | Date
    }
  }
}
