// TypesFromSerializers CacheKey 6c4b0577c0f847133fb6620fd0d6eb4c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface CategoriesIndex {
			id?: number
			categorizable_type: string
			created_at: string | Date
			description?: string
			name?: string
			qty: unknown
			slug: string
			updated_at: string | Date
		}

	}
}
