// TypesFromSerializers CacheKey e26d8e0eab9fd5acf6fcbc9c7809f931
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface CategoriesNew {
  id?: number
  categorizableType: string
  description?: string
  name?: string
}

