// TypesFromSerializers CacheKey a8391175ebed8fcdd21afc761932efdd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CategoriesOptions {
      id: number
      category_with_type: unknown
      name: string
      slug: string
    }
  }
}
