// TypesFromSerializers CacheKey cc5fa75812a2700169163420836942c6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CategoriesOptions {
      id: number
      category_with_type: unknown
      name: string
      slug: string
    }
  }
}
