// TypesFromSerializers CacheKey 12003a26bb94105f81db39a7bcf8d472
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface CategoriesOptions {
			id: number
			name?: string
		}

	}
}
