// TypesFromSerializers CacheKey d9e5627933e9f11ec3d80025c60cd957
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface CategoriesShow {
  id?: number
  categorizableType: string
  createdAt: string | Date
  description?: string
  name?: string
  plural: unknown
  slug: string
  updatedAt: string | Date
}

