// TypesFromSerializers CacheKey 245e28910525b25d4d6fb621067a90f6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CategoriesShow {
      id: number
      categorizable_type: string
      created_at: string | Date
      description?: string
      name: string
      plural: string
      qty: number
      slug: string
      updated_at: string | Date
    }
  }
}
