// TypesFromSerializers CacheKey dcd55c3135c1db42548bb6617e638f56
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CategoriesShow {
      id: number
      categorizable_type: string
      created_at: string | Date
      description?: string
      name: string
      plural: string
      qty: number
      slug: string
      updated_at: string | Date
    }
  }
}
