// TypesFromSerializers CacheKey fd0e014269c75e9cb82c77742a7e3400
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface CategoriesShow {
			id?: number
			categorizable_type: string
			created_at: string | Date
			description?: string
			name?: string
			plural: unknown
			slug: string
			updated_at: string | Date
		}

	}
}
