// TypesFromSerializers CacheKey 6d07a34e44a324db29928e7ecd24e323
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from '../Categories/Options'

declare global {
  namespace Schema {
    interface WebsitesFormData {
      id?: number
      category: CategoriesOptions
      contact_id: number
      name?: string
      notes?: string
      url: string
    }
  }
}
