// TypesFromSerializers CacheKey 3f091108fb92b361070f398f8fcfdea8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'
import type Contact from '../Contact'

declare global {
  namespace Schema {
    interface WebsitesFormData {
      id?: number
      category: Category
      contact: Contact
      contact_id: number
      name?: string
      notes?: string
      url: string
    }
  }
}
