// TypesFromSerializers CacheKey a4519dccae8e62cc806622ced0f6953c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from '../Categories/Options'

declare global {
  namespace Schema {
    interface WebsitesFormData {
      id?: number
      category: CategoriesOptions
      contact_id: number
      name?: string
      notes?: string
      url: string
    }
  }
}
