// TypesFromSerializers CacheKey 8f76d502f362c665b1a7367a1f04c246
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type User from '../User'

declare global {
  namespace Schema {
    interface PeopleBasic {
      id: number
      active: boolean
      created_at: string | Date
      department_id: unknown
      employee_number?: string
      first_name: string
      job_title?: string
      last_name: string
      location_id?: number
      manager_id?: number
      middle_name?: string
      name: string
      updated_at: string | Date
      user: User
      user_id?: number
    }
  }
}
