// TypesFromSerializers CacheKey 5a728ae8288a928f0de371979f5f5f67
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ContactsFormData from '../Contacts/FormData'
import type DepartmentsOptions from '../Departments/Options'
import type PeopleOptions from './Options'
import type PeopleFormDataPersonUserFormData from './FormData/PersonUserFormData'

declare global {
  namespace Schema {
    interface PeopleFormData {
      id?: number
      active: boolean
      contact?: ContactsFormData
      department?: DepartmentsOptions
      department_id: unknown
      employee_number?: string
      first_name: string
      job_title?: string
      last_name: string
      location_id?: number
      manager?: PeopleOptions
      manager_id?: number
      middle_name?: string
      name: string
      user?: PeopleFormDataPersonUserFormData
      user_id?: number
    }
  }
}
