// TypesFromSerializers CacheKey a6244ee092b0d0aafa57651143192ce6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Contact from '../Contact'
import type User from '../User'

export default interface PeopleNew {
  id?: number
  active: boolean
  contact: Contact
  employeeNumber?: string
  firstName?: string
  jobTitle?: string
  lastName?: string
  managerId?: number
  middleName?: string
  name: unknown
  user: User
}

