// TypesFromSerializers CacheKey cbb20a56fb0cb8ee64605716141d3a31
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleOptions {
      id?: number
      default_location_id: number
      name: string
    }
  }
}
