// TypesFromSerializers CacheKey 2eba505e67bbbc21c24b369ecbdfb360
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface PeopleOptions {
  id?: number
  defaultLocationId: unknown
  name: unknown
}

