// TypesFromSerializers CacheKey c76bcbe40f7094bcd2681b178478e47c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ActivitiesBasic from '../Activities/Basic'
import type ContactsBasic from '../Contacts/Basic'
import type DepartmentsBasic from '../Departments/Basic'
import type LocationsBasic from '../Locations/Basic'
import type PeopleBasic from './Basic'
import type AssignmentsBasic from '../Assignments/Basic'
import type UsersBasic from '../Users/Basic'

declare global {
  namespace Schema {
    interface PeopleShow {
      id: number
      active: boolean
      activities: ActivitiesBasic[]
      contact: ContactsBasic
      created_at: string | Date
      department: DepartmentsBasic
      department_id: unknown
      employee_number?: string
      first_name: string
      job_title?: string
      last_name: string
      location: LocationsBasic
      location_id?: number
      manager: PeopleBasic
      manager_id?: number
      middle_name?: string
      name: string
      possessions: AssignmentsBasic[]
      updated_at: string | Date
      user: UsersBasic
      user_id?: number
    }
  }
}
