// TypesFromSerializers CacheKey fa43998fa062d45709b5230292008860
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PhonesEdit {
      id: number
      category_id: number
      contact_id: number
      created_at: string | Date
      extension?: string
      notes?: string
      number: string
      updated_at: string | Date
    }
  }
}
