// TypesFromSerializers CacheKey bf89a20a2033d9cebe68d3694b547d52
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface PhonesFormData {
			id?: number
			category_id: number
			contact_id: number
			created_at: string | Date
			extension?: string
			notes?: string
			number: string
			updated_at: string | Date
		}

	}
}
