// TypesFromSerializers CacheKey 49f6e7343c1d7df83ceb6e519a9406e0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from '../Categories/Options'

declare global {
  namespace Schema {
    interface PhonesFormData {
      id?: number
      category: CategoriesOptions
      category_id: number
      contact_id: number
      created_at: string | Date
      extension?: string
      notes?: string
      number: string
      updated_at: string | Date
    }
  }
}
