// TypesFromSerializers CacheKey 4846a062b633e9ac1dd195baedf8ac67
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface ComponentsCheckout {
			id?: number
			assetTag?: string
			cost: unknown
			costCurrency: string
			createdAt: string | Date
			defaultLocationId?: number
			minQty?: number
			modelId: number
			name: string
			notes?: string
			purchasedAt?: string | Date
			qty?: number
			qtyAvailable: unknown
			serial?: string
			updatedAt: string | Date
			vendorId?: number
		}

	}
}
