// TypesFromSerializers CacheKey b9a7d4b4812b1d2bf42fa1050a58baa1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface ComponentsCheckout {
			id?: number
			asset_tag?: string
			cost: number
			cost_currency: string
			created_at: string | Date
			default_location_id?: number
			min_qty?: number
			model_id: number
			name: string
			notes?: string
			purchased_at?: string | Date
			qty?: number
			qty_available: number
			serial?: string
			updated_at: string | Date
			vendor_id?: number
		}

	}
}
