// TypesFromSerializers CacheKey fdfa0b598717c2cee79653ad3dfc5a41
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface ComponentsEdit {
			id?: number
			asset_tag?: string
			cost: unknown
			cost_currency: string
			default_location_id?: number
			min_qty?: number
			model_id: number
			name: string
			notes?: string
			purchased_at?: string | Date
			qty?: number
			qty_available: unknown
			serial?: string
			vendor_id?: number
		}

	}
}
