// TypesFromSerializers CacheKey a4270892257e6156936ec697deef5da8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../Money'
import type Category from '../Category'
import type Department from '../Department'
import type Manufacturer from '../Manufacturer'
import type Model from '../Model'
import type StatusLabelsOptions from '../StatusLabels/Options'
import type Vendor from '../Vendor'

declare global {
  namespace Schema {
    interface ComponentsIndex {
      id: number
      asset_tag?: string
      category: Category
      cost: Money
      cost_currency: string
      created_at: string | Date
      default_location_id?: number
      department: Department
      manufacturer: Manufacturer
      min_qty?: number
      model: Model
      model_id: number
      name: string
      notes?: string
      purchased_at?: string | Date
      qty?: number
      qty_available: number
      requestable: boolean
      serial?: string
      status_label: StatusLabelsOptions
      status_label_id?: number
      updated_at: string | Date
      vendor: Vendor
      vendor_id?: number
    }
  }
}
