// TypesFromSerializers CacheKey 9403653ff8f21a6a4a54e7940433e987
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ComponentsOptions {
      id: number
      created_at: string | Date
      name: string
      qty_available: number
      updated_at: string | Date
    }
  }
}
