// TypesFromSerializers CacheKey 6b2514facaf01be837887fd5fe7aa100
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ComponentsOptions {
      id: number
      name: string
      qty_available: number
    }
  }
}
