// TypesFromSerializers CacheKey cdc02714b3715378da070f109047a9b7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Activity from '../Activity'
import type Assignment from '../Assignment'
import type Category from '../Category'
import type Location from '../Location'
import type Department from '../Department'
import type Manufacturer from '../Manufacturer'
import type Model from '../Model'
import type Purchase from '../Purchase'
import type Vendor from '../Vendor'

export default interface ComponentsShow {
  id?: number
  activities: Activity[]
  assetTag?: string
  assignments: Assignment[]
  category: Category
  cost: unknown
  costCurrency: string
  createdAt: string | Date
  defaultLocation: Location
  defaultLocationId?: number
  department: Department
  manufacturer: Manufacturer
  minQty?: number
  model: Model
  modelId: number
  name: string
  notes?: string
  purchase: Purchase
  purchasedAt?: string | Date
  qty?: number
  qtyAvailable: unknown
  serial?: string
  updatedAt: string | Date
  vendor: Vendor
  vendorId?: number
}

