// TypesFromSerializers CacheKey 73216124a8e699b5bf67097cd5f1757d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface AssignmentsEdit {
			id: number
			active: boolean
			assign_toable_id: number
			assign_toable_type: TAssignToable
			assignable_id: number
			assignable_type: TAssignable
			assigned_at?: string | Date
			created_at: string | Date
			created_by_id?: number
			expected_at?: string | Date
			location_id: number
			notes?: string
			qty: number
			returned_at?: string | Date
			status?: number
			updated_at: string | Date
		}

	}
}
