// TypesFromSerializers CacheKey bb70fa3f0c70801a00c6c75820b83256
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AssignmentsEdit {
  id?: unknown
  active: unknown
  assignToableId: unknown
  assignToableType: unknown
  assignableId: unknown
  assignableType: unknown
  assignedAt: unknown
  createdAt: unknown
  createdById: unknown
  expectedAt: unknown
  locationId: unknown
  notes: unknown
  qty: unknown
  returnedAt: unknown
  status: unknown
  updatedAt: unknown
}

