// TypesFromSerializers CacheKey 069fcd70126ac1141fa53e79728d0e84
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface AssignmentsNew {
			id?: number
			active: boolean
			assign_toable_id: number
			assign_toable_type: string
			assignable_id: number
			assignable_type: string
			assigned_at?: string | Date
			created_at: string | Date
			created_by_id?: number
			expected_at?: string | Date
			location_id: number
			notes?: string
			qty: number
			returned_at?: string | Date
			status?: number
			updated_at: string | Date
		}

	}
}
