// TypesFromSerializers CacheKey 2a8785044b550121072afa051a65a1eb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface AssignmentsNew {
			id?: number
			active: boolean
			assignToableId: number
			assignToableType: string
			assignableId: number
			assignableType: string
			assignedAt?: string | Date
			createdAt: string | Date
			createdById?: number
			expectedAt?: string | Date
			locationId: number
			notes?: string
			qty: number
			returnedAt?: string | Date
			status?: number
			updatedAt: string | Date
		}

	}
}
