// TypesFromSerializers CacheKey 23d5692fe4ef134ed0d6d7f8b8da41ca
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface AssignmentsShallow {
      id?: number
      active: boolean
      assign_toable_id: number
      assign_toable_type: AssignToableTypes
      assignable_id: number
      assignable_type: AssignableTypes
      assigned_at?: string | Date
      created_at: string | Date
      created_by_id?: number
      expected_at?: string | Date
      location_id: number
      notes?: string
      qty: number
      returned_at?: string | Date
      status?: number
      updated_at: string | Date
    }
  }
}
