// TypesFromSerializers CacheKey f7291cc5afd63d83266fb1707227b689
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ActivityUserActivity from '../Activity/UserActivity'
import type ActivityPersonActivity from '../Activity/PersonActivity'

declare global {
  namespace Schema {
    interface ActivitiesDashboard {
      id: number
      created_at: string | Date
      key?: string
      owner: ActivityUserActivity
      owner_id?: number
      owner_type?: string
      parameters: Record<string, string>
      person: ActivityPersonActivity
      recipient_id?: number
      recipient_type?: string
      route: string
      trackable_id?: number
      trackable_type?: string
      updated_at: string | Date
    }
  }
}
