// TypesFromSerializers CacheKey cc814b069d7694757f009b2c4429250f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Address from '../Address'
import type Email from '../Email'
import type Phone from '../Phone'
import type Website from '../Website'

declare global {
  namespace Schema {
    interface ContactsFormData {
      id?: number
      addresses: Address[]
      contactable_id?: number
      contactable_type?: string
      emails: Email[]
      notes?: string
      phones: Phone[]
      primary_address_id?: number
      primary_email_id?: number
      primary_phone_id?: number
      websites: Website[]
    }
  }
}
