// TypesFromSerializers CacheKey b9a9bc770ec7bc3a0dacbf0914fc6adb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface ContactsNew {
			id?: number
			contactable_id?: number
			contactable_type?: string
			created_at: string | Date
			notes?: string
			primary_address_id?: number
			primary_email_id?: number
			primary_phone_id?: number
			updated_at: string | Date
		}

	}
}
