// TypesFromSerializers CacheKey f4d54ec5a89aa51992cf81070db12d43
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface ContactsNew {
			id?: number
			contactableId?: number
			contactableType?: string
			createdAt: string | Date
			notes?: string
			primaryAddressId?: number
			primaryEmailId?: number
			primaryPhoneId?: number
			updatedAt: string | Date
		}

	}
}
