// TypesFromSerializers CacheKey 30fb5b3f0e87dc319d82df88c4cda312
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface AccessoriesCheckin {
			id: number
			asset_tag?: string
			cost: unknown
			cost_currency: string
			default_location_id?: number
			min_qty?: number
			model_id: number
			name: string
			notes?: string
			qty?: number
			qty_available: unknown
			requestable: boolean
			serial?: string
			vendor_id?: number
		}

	}
}
