// TypesFromSerializers CacheKey 6f0f6c2b66b6966fbbf75b99f17a5b3a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface AccessoriesCheckout {
			id?: number
			assetTag?: string
			cost: unknown
			costCurrency: string
			defaultLocationId?: number
			minQty?: number
			modelId: number
			name: string
			notes?: string
			qty?: number
			qtyAvailable: unknown
			requestable: boolean
			serial?: string
			vendorId?: number
		}

	}
}
