// TypesFromSerializers CacheKey 0931f6ab872f7cddbb6910d213925cdd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface AccessoriesCheckout {
			id: number
			asset_tag?: string
			cost: unknown
			cost_currency: string
			default_location_id?: number
			min_qty?: number
			model_id: number
			name: string
			notes?: string
			qty?: number
			qty_available: unknown
			requestable: boolean
			serial?: string
			vendor_id?: number
		}

	}
}
