// TypesFromSerializers CacheKey 66d0d1ef69ea538e0c4884d134bc3378
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AccessoriesEdit {
  id?: number
  assetTag?: string
  cost: unknown
  costCurrency: string
  defaultLocationId?: number
  minQty?: number
  modelId: number
  name: string
  notes?: string
  qty?: number
  qtyAvailable: unknown
  requestable: boolean
  serial?: string
  vendorId?: number
}

