// TypesFromSerializers CacheKey b01f3361ee471a38ff703319716a836a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface AccessoriesEdit {
      id: number
      asset_tag?: string
      cost: number
      cost_currency: string
      default_location_id?: number
      min_qty?: number
      model_id: number
      name: string
      notes?: string
      qty?: number
      qty_available: number
      requestable: boolean
      serial?: string
      vendor_id?: number
    }
  }
}
