// TypesFromSerializers CacheKey 33d1365224219c19e9d3cb8a2a5493a6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface AccessoriesFormData {
      id?: number
      asset_tag?: string
      cost: unknown
      cost_currency: string
      default_location_id?: number
      min_qty?: number
      model_id: number
      name: string
      notes?: string
      qty?: number
      qty_available: number
      requestable: boolean
      serial?: string
      vendor_id?: number
    }
  }
}
