// TypesFromSerializers CacheKey 7fd4e72b4f60d774a6a8281db1abe2ad
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../Money'
import type Category from '../Category'
import type LocationsOptions from '../Locations/Options'
import type Manufacturer from '../Manufacturer'
import type ModelsOptions from '../Models/Options'
import type StatusLabel from '../StatusLabel'
import type VendorsOptions from '../Vendors/Options'

declare global {
  namespace Schema {
    interface AccessoriesFormData {
      id: number
      asset_tag?: string
      category: Category
      cost: Money
      cost_currency: string
      default_location: LocationsOptions
      default_location_id?: number
      manufacturer: Manufacturer
      min_qty?: number
      model: ModelsOptions
      model_id: number
      name: string
      notes?: string
      purchased_at?: string | Date
      qty?: number
      qty_available: number
      requestable: boolean
      serial?: string
      status_label: StatusLabel
      status_label_id?: number
      vendor: VendorsOptions
      vendor_id?: number
    }
  }
}
