// TypesFromSerializers CacheKey cade1cc4f1bfe908f899072b456e8792
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Activity } from '../Activity'
import type { Assignment } from '../Assignment'
import type { Category } from '../Category'
import type { Company } from '../Company'
import type { Location } from '../Location'
import type { Department } from '../Department'
import type { Manufacturer } from '../Manufacturer'
import type { Model } from '../Model'
import type { Purchase } from '../Purchase'
import type { StatusLabel } from '../StatusLabel'
import type { Vendor } from '../Vendor'

declare export global {
	declare namespace Schema {
		export interface AccessoriesIndex {
			id: number
			activities: Activity[]
			asset_tag?: string
			assignments: Assignment[]
			category: Category
			company: Company
			cost: unknown
			cost_currency: string
			created_at: string | Date
			default_location: Location
			default_location_id?: number
			department: Department
			manufacturer: Manufacturer
			min_qty?: number
			model: Model
			model_id: number
			name: string
			notes?: string
			purchase: Purchase
			purchased_at?: string | Date
			qty?: number
			qty_available: unknown
			requestable: boolean
			serial?: string
			status_label: StatusLabel
			type: string
			updated_at: string | Date
			vendor: Vendor
			vendor_id?: number
		}

	}
}
