// TypesFromSerializers CacheKey 741595d2781854f0335a4e82985968c9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface AccessoriesNew {
  id?: number
  assetTag?: string
  cost: unknown
  costCurrency: string
  defaultLocationId?: number
  minQty?: number
  modelId: number
  name: string
  notes?: string
  qty?: number
  qtyAvailable: unknown
  requestable: boolean
  serial?: string
  vendorId?: number
}

