// TypesFromSerializers CacheKey 99db2c37b1b3f7bb85268f69f7d8506b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface AccessoriesOptions {
      id: number
      name: string
      qty_available: number
    }
  }
}
