// TypesFromSerializers CacheKey 72a91c39d895a13e7971146562c40201
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../Money'
import type Activity from '../Activity'
import type AssignmentsShow from '../Assignments/Show'
import type Category from '../Category'
import type Company from '../Company'
import type Location from '../Location'
import type Department from '../Department'
import type DocumentationsIndex from '../Documentations/Index'
import type Manufacturer from '../Manufacturer'
import type Model from '../Model'
import type Purchase from '../Purchase'
import type StatusLabel from '../StatusLabel'
import type Vendor from '../Vendor'

declare global {
  namespace Schema {
    interface AccessoriesShow {
      id: number
      activities: Activity[]
      asset_tag?: string
      assignments: AssignmentsShow[]
      category: Category
      company: Company
      cost: Money
      cost_currency: string
      created_at: string | Date
      default_location: Location
      default_location_id?: number
      department: Department
      documentations: DocumentationsIndex[]
      manufacturer: Manufacturer
      min_qty?: number
      model: Model
      model_id: number
      name: string
      notes?: string
      purchase: Purchase
      purchased_at?: string | Date
      qty?: number
      qty_available: number
      requestable: boolean
      serial?: string
      status_label: StatusLabel
      status_label_id?: number
      updated_at: string | Date
      vendor: Vendor
      vendor_id?: number
    }
  }
}
