// TypesFromSerializers CacheKey 4b2f7c8773d424e891edfbeda8ad3f16
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../Money'
import type Category from '../Category'
import type Manufacturer from '../Manufacturer'
import type Vendor from '../Vendor'

declare global {
  namespace Schema {
    interface LicensesBasic {
      id: number
      category: Category
      category_id: number
      cost: Money
      cost_currency: string
      created_at: string | Date
      expires_at?: string | Date
      key?: string
      licenser_email?: string
      licenser_name?: string
      maintained: boolean
      manufacturer: Manufacturer
      manufacturer_id: number
      name: string
      notes?: string
      purchased_at?: string | Date
      qty?: number
      qty_available: number
      reassignable: boolean
      status_label_id?: number
      terminates_at?: string | Date
      updated_at: string | Date
      vendor: Vendor
      vendor_id?: number
    }
  }
}
