// TypesFromSerializers CacheKey d65617ef5e1671cef3005c78260f992c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface LicensesCheckin {
			id?: number
			categoryId: number
			cost: unknown
			costCurrency: string
			createdAt: string | Date
			expiresAt?: string | Date
			key?: string
			licenserEmail?: string
			licenserName?: string
			maintained: boolean
			manufacturerId: number
			name: string
			notes?: string
			purchasedAt?: string | Date
			qty?: number
			qtyAvailable: unknown
			reassignable: boolean
			terminatesAt?: string | Date
			updatedAt: string | Date
			vendorId?: number
		}

	}
}
