// TypesFromSerializers CacheKey 819b0ca9834b2f378c0fd49daa34cae4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface LicensesCheckout {
			id?: number
			category_id: number
			cost: unknown
			cost_currency: string
			created_at: string | Date
			expires_at?: string | Date
			key?: string
			licenser_email?: string
			licenser_name?: string
			maintained: boolean
			manufacturer_id: number
			name: string
			notes?: string
			purchased_at?: string | Date
			qty?: number
			qty_available: unknown
			reassignable: boolean
			terminates_at?: string | Date
			updated_at: string | Date
			vendor_id?: number
		}

	}
}
