// TypesFromSerializers CacheKey bc90ba5a26749a52c9c2811e082e99e2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CategoriesOptions from '../Categories/Options'
import type ManufacturersOptions from '../Manufacturers/Options'
import type VendorsOptions from '../Vendors/Options'

declare global {
  namespace Schema {
    interface LicensesEdit {
      id: number
      category: CategoriesOptions
      category_id: number
      cost: number
      cost_currency: string
      created_at: string | Date
      expires_at?: string | Date
      key?: string
      licenser_email?: string
      licenser_name?: string
      maintained: boolean
      manufacturer: ManufacturersOptions
      manufacturer_id: number
      name: string
      notes?: string
      purchased_at?: string | Date
      qty?: number
      qty_available: number
      reassignable: boolean
      status_label_id?: number
      terminates_at?: string | Date
      updated_at: string | Date
      vendor: VendorsOptions
      vendor_id?: number
    }
  }
}
