// TypesFromSerializers CacheKey 1ece950991c2bfd64cc344ffa839ec08
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface LicensesEdit {
  id?: number
  categoryId: number
  cost: unknown
  costCurrency: string
  expiresAt?: string | Date
  key?: string
  licenserEmail?: string
  licenserName?: string
  maintained: boolean
  manufacturerId: number
  name: string
  notes?: string
  purchasedAt?: string | Date
  qty?: number
  qtyAvailable: unknown
  reassignable: boolean
  terminatesAt?: string | Date
  vendorId?: number
}

