// TypesFromSerializers CacheKey cc29f569cf9301e506bbda557d546aff
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Money from '../../Money'
import type CategoriesOptions from '../Categories/Options'
import type ManufacturersOptions from '../Manufacturers/Options'
import type VendorsOptions from '../Vendors/Options'

declare global {
  namespace Schema {
    interface LicensesEdit {
      id: number
      category: CategoriesOptions
      category_id: number
      cost: Money
      cost_currency: string
      expires_at?: string | Date
      key?: string
      licenser_email?: string
      licenser_name?: string
      maintained: boolean
      manufacturer: ManufacturersOptions
      manufacturer_id: number
      name: string
      notes?: string
      purchased_at?: string | Date
      qty?: number
      qty_available: number
      reassignable: boolean
      status_label_id?: number
      terminates_at?: string | Date
      vendor: VendorsOptions
      vendor_id?: number
    }
  }
}
