// TypesFromSerializers CacheKey 15d459aa33f68e6ff9b2f67a276d5add
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Category from '../Category'
import type Department from '../Department'
import type Manufacturer from '../Manufacturer'
import type Vendor from '../Vendor'

export default interface LicensesIndex {
  id?: number
  category: Category
  categoryId: number
  cost: unknown
  costCurrency: string
  createdAt: string | Date
  department: Department
  expiresAt?: string | Date
  key?: string
  licenserEmail?: string
  licenserName?: string
  maintained: boolean
  manufacturer: Manufacturer
  manufacturerId: number
  name: string
  notes?: string
  purchasedAt?: string | Date
  qty?: number
  qtyAvailable: unknown
  reassignable: boolean
  terminatesAt?: string | Date
  updatedAt: string | Date
  vendor: Vendor
  vendorId?: number
}

