// TypesFromSerializers CacheKey 679dea86e7a4dc29463345f6ab42bfe6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type { Activity } from '../Activity'
import type { Assignment } from '../Assignment'
import type { Category } from '../Category'
import type { Department } from '../Department'
import type { Manufacturer } from '../Manufacturer'
import type { Purchase } from '../Purchase'
import type { Vendor } from '../Vendor'

declare global {
	 declare namespace Schema {
		export interface LicensesShow {
			id?: number
			activities: Activity[]
			assignments: Assignment[]
			category: Category
			categoryId: number
			cost: unknown
			costCurrency: string
			createdAt: string | Date
			department: Department
			expiresAt?: string | Date
			key?: string
			licenserEmail?: string
			licenserName?: string
			maintained: boolean
			manufacturer: Manufacturer
			manufacturerId: number
			name: string
			notes?: string
			purchase: Purchase
			purchasedAt?: string | Date
			qty?: number
			qtyAvailable: unknown
			reassignable: boolean
			terminatesAt?: string | Date
			updatedAt: string | Date
			vendor: Vendor
			vendorId?: number
		}

	}
}
