// TypesFromSerializers CacheKey 272f1ec8ab307cb7a28a2ea8d13c11ed
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ManufacturersOptions from '../Manufacturers/Options'
import type StatusLabelsBasic from '../StatusLabels/Basic'

declare global {
  namespace Schema {
    interface LicensesSpotlight {
      id: string
      category_id: number
      manufacturer: ManufacturersOptions
      manufacturer_id: number
      name: string
      status_label: StatusLabelsBasic
      status_label_id?: number
      vendor_id?: number
    }
  }
}
