// TypesFromSerializers CacheKey 6a36db896a8aaa22a98957bb7845769b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface TicketStatusesEdit {
      id?: number
      name?: string
    }
  }
}
