// TypesFromSerializers CacheKey 3cf9e389dc2991a45f058ccb98574c12
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface TicketStatusesEdit {
      id?: number
      name: string
    }
  }
}
