// TypesFromSerializers CacheKey c4167c3a55feef70ca1286796afe8863
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface TicketStatusesFormData {
      id?: number
      name?: string
    }
  }
}
