// TypesFromSerializers CacheKey dbbc7699cf95d799fcd71b87d2bae3cb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare global {
	 declare namespace Schema {
		export interface TicketStatusesIndex {
			id?: number
			createdAt: string | Date
			name?: string
			updatedAt: string | Date
		}

	}
}
