// TypesFromSerializers CacheKey ac7a75c26b9cd4f61e39ae6138ba1b7d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

declare export global {
	declare namespace Schema {
		export interface TicketStatusesIndex {
			id?: number
			created_at: string | Date
			name?: string
			updated_at: string | Date
		}

	}
}
