// TypesFromSerializers CacheKey a57bfb20f8e3a4f83b31c3893a817e4a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface TicketStatusesShow {
  id?: number
  createdAt: string | Date
  name?: string
  updatedAt: string | Date
}

