// TypesFromSerializers CacheKey aac73eb0ab7512e6839b8570d73f3482
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface TicketStatusesShow {
      id?: number
      created_at: string | Date
      name?: string
      updated_at: string | Date
    }
  }
}
